// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chofer.sql

package dto

import (
	"context"
	"database/sql"
	"time"
)

const createChofer = `-- name: CreateChofer :execresult
INSERT INTO chofer (nombre, fechaNac, telefono, email, tipoLicencia, nacionalidad, fechaCreacion, fechaActualizacion)
VALUES (?, ?, ?, ?, ?, ?, now(), now())
`

type CreateChoferParams struct {
	Nombre       string    `json:"nombre"`
	Fechanac     time.Time `json:"fechanac"`
	Telefono     string    `json:"telefono"`
	Email        string    `json:"email"`
	Tipolicencia string    `json:"tipolicencia"`
	Nacionalidad string    `json:"nacionalidad"`
}

func (q *Queries) CreateChofer(ctx context.Context, arg CreateChoferParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChofer,
		arg.Nombre,
		arg.Fechanac,
		arg.Telefono,
		arg.Email,
		arg.Tipolicencia,
		arg.Nacionalidad,
	)
}

const deleteChofer = `-- name: DeleteChofer :execresult
DELETE FROM chofer WHERE idChofer = ?
`

func (q *Queries) DeleteChofer(ctx context.Context, idchofer int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteChofer, idchofer)
}

const getAllChofer = `-- name: GetAllChofer :many
SELECT idchofer, nombre, fechanac, telefono, email, tipolicencia, nacionalidad, fechacreacion, fechaactualizacion FROM chofer
`

func (q *Queries) GetAllChofer(ctx context.Context) ([]Chofer, error) {
	rows, err := q.db.QueryContext(ctx, getAllChofer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chofer
	for rows.Next() {
		var i Chofer
		if err := rows.Scan(
			&i.Idchofer,
			&i.Nombre,
			&i.Fechanac,
			&i.Telefono,
			&i.Email,
			&i.Tipolicencia,
			&i.Nacionalidad,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChoferById = `-- name: GetChoferById :one
SELECT idchofer, nombre, fechanac, telefono, email, tipolicencia, nacionalidad, fechacreacion, fechaactualizacion FROM chofer WHERE idChofer = ?
`

func (q *Queries) GetChoferById(ctx context.Context, idchofer int32) (Chofer, error) {
	row := q.db.QueryRowContext(ctx, getChoferById, idchofer)
	var i Chofer
	err := row.Scan(
		&i.Idchofer,
		&i.Nombre,
		&i.Fechanac,
		&i.Telefono,
		&i.Email,
		&i.Tipolicencia,
		&i.Nacionalidad,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const updateChofer = `-- name: UpdateChofer :execresult
UPDATE chofer 
SET nombre = ?, 
    fechaNac = ?, 
    telefono = ?, 
    email = ?, 
    tipoLicencia = ?, 
    nacionalidad = ?,
    fechaActualizacion = now()
WHERE idChofer = ?
`

type UpdateChoferParams struct {
	Nombre       string    `json:"nombre"`
	Fechanac     time.Time `json:"fechanac"`
	Telefono     string    `json:"telefono"`
	Email        string    `json:"email"`
	Tipolicencia string    `json:"tipolicencia"`
	Nacionalidad string    `json:"nacionalidad"`
	Idchofer     int32     `json:"idchofer"`
}

func (q *Queries) UpdateChofer(ctx context.Context, arg UpdateChoferParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateChofer,
		arg.Nombre,
		arg.Fechanac,
		arg.Telefono,
		arg.Email,
		arg.Tipolicencia,
		arg.Nacionalidad,
		arg.Idchofer,
	)
}
