// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cliente.sql

package dto

import (
	"context"
	"database/sql"
	"time"
)

const createCliente = `-- name: CreateCliente :execresult
INSERT INTO Cliente (nombre, telefono, nacionalidad, fechaRegistro, fechaCreacion, fechaActualizacion)
VALUES (?, ?, ?, ?, now(), now())
`

type CreateClienteParams struct {
	Nombre        string    `json:"nombre"`
	Telefono      int32     `json:"telefono"`
	Nacionalidad  string    `json:"nacionalidad"`
	Fecharegistro time.Time `json:"fecharegistro"`
}

func (q *Queries) CreateCliente(ctx context.Context, arg CreateClienteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCliente,
		arg.Nombre,
		arg.Telefono,
		arg.Nacionalidad,
		arg.Fecharegistro,
	)
}

const deleteCliente = `-- name: DeleteCliente :execresult
DELETE FROM Cliente WHERE idCliente = ?
`

func (q *Queries) DeleteCliente(ctx context.Context, idcliente int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCliente, idcliente)
}

const getAllCliente = `-- name: GetAllCliente :many
SELECT idcliente, nombre, telefono, nacionalidad, fecharegistro, fechacreacion, fechaactualizacion FROM Cliente
`

func (q *Queries) GetAllCliente(ctx context.Context) ([]Cliente, error) {
	rows, err := q.db.QueryContext(ctx, getAllCliente)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cliente
	for rows.Next() {
		var i Cliente
		if err := rows.Scan(
			&i.Idcliente,
			&i.Nombre,
			&i.Telefono,
			&i.Nacionalidad,
			&i.Fecharegistro,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClienteById = `-- name: GetClienteById :one
SELECT idcliente, nombre, telefono, nacionalidad, fecharegistro, fechacreacion, fechaactualizacion FROM Cliente WHERE idCliente = ?
`

func (q *Queries) GetClienteById(ctx context.Context, idcliente int32) (Cliente, error) {
	row := q.db.QueryRowContext(ctx, getClienteById, idcliente)
	var i Cliente
	err := row.Scan(
		&i.Idcliente,
		&i.Nombre,
		&i.Telefono,
		&i.Nacionalidad,
		&i.Fecharegistro,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const updateCliente = `-- name: UpdateCliente :execresult
UPDATE Cliente 
SET nombre = ?, 
    telefono = ?, 
    nacionalidad = ?,
    fechaRegistro = ?, 
    fechaActualizacion = now()
WHERE idCliente = ?
`

type UpdateClienteParams struct {
	Nombre        string    `json:"nombre"`
	Telefono      int32     `json:"telefono"`
	Nacionalidad  string    `json:"nacionalidad"`
	Fecharegistro time.Time `json:"fecharegistro"`
	Idcliente     int32     `json:"idcliente"`
}

func (q *Queries) UpdateCliente(ctx context.Context, arg UpdateClienteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCliente,
		arg.Nombre,
		arg.Telefono,
		arg.Nacionalidad,
		arg.Fecharegistro,
		arg.Idcliente,
	)
}
