// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: detallereserva.sql

package dto

import (
	"context"
	"database/sql"
	"time"
)

const createDetalleReserva = `-- name: CreateDetalleReserva :execresult
INSERT INTO DetalleReserva (
    idReserva,
    idTour,
    idGuia,
    idChofer,
    idUbicacion,
    idIdioma,
    fechaTour,
    precioUnitario,
    fechaCreacion,
    fechaActualizacion
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, now(), now())
`

type CreateDetalleReservaParams struct {
	Idreserva      int32     `json:"idreserva"`
	Idtour         int32     `json:"idtour"`
	Idguia         int32     `json:"idguia"`
	Idchofer       int32     `json:"idchofer"`
	Idubicacion    int32     `json:"idubicacion"`
	Ididioma       int32     `json:"ididioma"`
	Fechatour      time.Time `json:"fechatour"`
	Preciounitario string    `json:"preciounitario"`
}

func (q *Queries) CreateDetalleReserva(ctx context.Context, arg CreateDetalleReservaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDetalleReserva,
		arg.Idreserva,
		arg.Idtour,
		arg.Idguia,
		arg.Idchofer,
		arg.Idubicacion,
		arg.Ididioma,
		arg.Fechatour,
		arg.Preciounitario,
	)
}

const deleteDetalleReserva = `-- name: DeleteDetalleReserva :execresult
DELETE FROM DetalleReserva WHERE idDetalleReserva = ?
`

func (q *Queries) DeleteDetalleReserva(ctx context.Context, iddetallereserva int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteDetalleReserva, iddetallereserva)
}

const getAllDetalleReserva = `-- name: GetAllDetalleReserva :many
SELECT
    dr.idDetalleReserva,
    dr.idReserva,
    dr.fechaTour,
    dr.precioUnitario,
    dr.fechaCreacion,
    dr.fechaActualizacion,

    -- Estado de la Reserva padre
    e.nombre    AS nombreEstado,

    -- Tour
    t.nombre    AS tourNombre,
    t.horario,
    t.duracion,
    t.precioBase,

    -- Guia
    g.nombre    AS guiaNombre,
    g.telefono  AS guiaTelefono,

    -- Chofer
    ch.nombre       AS choferNombre,
    ch.telefono     AS choferTelefono,
    ch.tipoLicencia AS choferLicencia,

    -- Vehiculo del Chofer
    v.matricula     AS vehiculoMatricula,
    v.modelo        AS vehiculoModelo,
    v.capacidad     AS vehiculoCapacidad,

    -- Ubicacion
    u.nombre    AS ubicacionNombre,
    u.direccion,

    -- Idioma
    i.nombre    AS idiomaNombre

FROM DetalleReserva dr

JOIN Reserva r      ON dr.idReserva     = r.idReserva
JOIN EstadoReserva e ON r.idEstadoReserva = e.idEstadoReserva
JOIN Tour t         ON dr.idTour        = t.idTour
JOIN Guia g         ON dr.idGuia        = g.idGuia
JOIN Chofer ch      ON dr.idChofer      = ch.idChofer
JOIN Ubicacion u    ON dr.idUbicacion   = u.idUbicacion
JOIN Idioma i       ON dr.idIdioma      = i.idIdioma
LEFT JOIN Vehiculo v ON ch.idChofer     = v.idChofer
`

type GetAllDetalleReservaRow struct {
	Iddetallereserva   int32          `json:"iddetallereserva"`
	Idreserva          int32          `json:"idreserva"`
	Fechatour          time.Time      `json:"fechatour"`
	Preciounitario     string         `json:"preciounitario"`
	Fechacreacion      sql.NullTime   `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime   `json:"fechaactualizacion"`
	Nombreestado       string         `json:"nombreestado"`
	Tournombre         string         `json:"tournombre"`
	Horario            string         `json:"horario"`
	Duracion           int32          `json:"duracion"`
	Preciobase         string         `json:"preciobase"`
	Guianombre         string         `json:"guianombre"`
	Guiatelefono       string         `json:"guiatelefono"`
	Chofernombre       string         `json:"chofernombre"`
	Chofertelefono     string         `json:"chofertelefono"`
	Choferlicencia     string         `json:"choferlicencia"`
	Vehiculomatricula  sql.NullString `json:"vehiculomatricula"`
	Vehiculomodelo     sql.NullString `json:"vehiculomodelo"`
	Vehiculocapacidad  sql.NullInt32  `json:"vehiculocapacidad"`
	Ubicacionnombre    string         `json:"ubicacionnombre"`
	Direccion          string         `json:"direccion"`
	Idiomanombre       string         `json:"idiomanombre"`
}

func (q *Queries) GetAllDetalleReserva(ctx context.Context) ([]GetAllDetalleReservaRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllDetalleReserva)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDetalleReservaRow
	for rows.Next() {
		var i GetAllDetalleReservaRow
		if err := rows.Scan(
			&i.Iddetallereserva,
			&i.Idreserva,
			&i.Fechatour,
			&i.Preciounitario,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
			&i.Nombreestado,
			&i.Tournombre,
			&i.Horario,
			&i.Duracion,
			&i.Preciobase,
			&i.Guianombre,
			&i.Guiatelefono,
			&i.Chofernombre,
			&i.Chofertelefono,
			&i.Choferlicencia,
			&i.Vehiculomatricula,
			&i.Vehiculomodelo,
			&i.Vehiculocapacidad,
			&i.Ubicacionnombre,
			&i.Direccion,
			&i.Idiomanombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDetalleReservaById = `-- name: GetDetalleReservaById :one
SELECT
    dr.idDetalleReserva,
    dr.idReserva,
    dr.fechaTour,
    dr.precioUnitario,
    dr.fechaCreacion,
    dr.fechaActualizacion,

    e.nombre    AS nombreEstado,

    t.nombre    AS tourNombre,
    t.horario,
    t.duracion,
    t.precioBase,

    g.nombre    AS guiaNombre,
    g.telefono  AS guiaTelefono,

    ch.nombre       AS choferNombre,
    ch.telefono     AS choferTelefono,
    ch.tipoLicencia AS choferLicencia,

    v.matricula     AS vehiculoMatricula,
    v.modelo        AS vehiculoModelo,
    v.capacidad     AS vehiculoCapacidad,

    u.nombre    AS ubicacionNombre,
    u.direccion,

    i.nombre    AS idiomaNombre

FROM DetalleReserva dr

JOIN Reserva r       ON dr.idReserva      = r.idReserva
JOIN EstadoReserva e ON r.idEstadoReserva = e.idEstadoReserva
JOIN Tour t          ON dr.idTour         = t.idTour
JOIN Guia g          ON dr.idGuia         = g.idGuia
JOIN Chofer ch       ON dr.idChofer       = ch.idChofer
JOIN Ubicacion u     ON dr.idUbicacion    = u.idUbicacion
JOIN Idioma i        ON dr.idIdioma       = i.idIdioma
LEFT JOIN Vehiculo v ON ch.idChofer       = v.idChofer

WHERE dr.idDetalleReserva = ?
`

type GetDetalleReservaByIdRow struct {
	Iddetallereserva   int32          `json:"iddetallereserva"`
	Idreserva          int32          `json:"idreserva"`
	Fechatour          time.Time      `json:"fechatour"`
	Preciounitario     string         `json:"preciounitario"`
	Fechacreacion      sql.NullTime   `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime   `json:"fechaactualizacion"`
	Nombreestado       string         `json:"nombreestado"`
	Tournombre         string         `json:"tournombre"`
	Horario            string         `json:"horario"`
	Duracion           int32          `json:"duracion"`
	Preciobase         string         `json:"preciobase"`
	Guianombre         string         `json:"guianombre"`
	Guiatelefono       string         `json:"guiatelefono"`
	Chofernombre       string         `json:"chofernombre"`
	Chofertelefono     string         `json:"chofertelefono"`
	Choferlicencia     string         `json:"choferlicencia"`
	Vehiculomatricula  sql.NullString `json:"vehiculomatricula"`
	Vehiculomodelo     sql.NullString `json:"vehiculomodelo"`
	Vehiculocapacidad  sql.NullInt32  `json:"vehiculocapacidad"`
	Ubicacionnombre    string         `json:"ubicacionnombre"`
	Direccion          string         `json:"direccion"`
	Idiomanombre       string         `json:"idiomanombre"`
}

func (q *Queries) GetDetalleReservaById(ctx context.Context, iddetallereserva int32) (GetDetalleReservaByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getDetalleReservaById, iddetallereserva)
	var i GetDetalleReservaByIdRow
	err := row.Scan(
		&i.Iddetallereserva,
		&i.Idreserva,
		&i.Fechatour,
		&i.Preciounitario,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
		&i.Nombreestado,
		&i.Tournombre,
		&i.Horario,
		&i.Duracion,
		&i.Preciobase,
		&i.Guianombre,
		&i.Guiatelefono,
		&i.Chofernombre,
		&i.Chofertelefono,
		&i.Choferlicencia,
		&i.Vehiculomatricula,
		&i.Vehiculomodelo,
		&i.Vehiculocapacidad,
		&i.Ubicacionnombre,
		&i.Direccion,
		&i.Idiomanombre,
	)
	return i, err
}

const getDetalleReservaByReserva = `-- name: GetDetalleReservaByReserva :many
SELECT
    dr.idDetalleReserva,
    dr.idReserva,
    dr.fechaTour,
    dr.precioUnitario,
    dr.fechaCreacion,
    dr.fechaActualizacion,

    e.nombre    AS nombreEstado,

    t.nombre    AS tourNombre,
    t.horario,
    t.duracion,
    t.precioBase,

    g.nombre    AS guiaNombre,
    g.telefono  AS guiaTelefono,

    ch.nombre       AS choferNombre,
    ch.telefono     AS choferTelefono,
    ch.tipoLicencia AS choferLicencia,

    v.matricula     AS vehiculoMatricula,
    v.modelo        AS vehiculoModelo,
    v.capacidad     AS vehiculoCapacidad,

    u.nombre    AS ubicacionNombre,
    u.direccion,

    i.nombre    AS idiomaNombre

FROM DetalleReserva dr

JOIN Reserva r       ON dr.idReserva      = r.idReserva
JOIN EstadoReserva e ON r.idEstadoReserva = e.idEstadoReserva
JOIN Tour t          ON dr.idTour         = t.idTour
JOIN Guia g          ON dr.idGuia         = g.idGuia
JOIN Chofer ch       ON dr.idChofer       = ch.idChofer
JOIN Ubicacion u     ON dr.idUbicacion    = u.idUbicacion
JOIN Idioma i        ON dr.idIdioma       = i.idIdioma
LEFT JOIN Vehiculo v ON ch.idChofer       = v.idChofer

WHERE dr.idReserva = ?
`

type GetDetalleReservaByReservaRow struct {
	Iddetallereserva   int32          `json:"iddetallereserva"`
	Idreserva          int32          `json:"idreserva"`
	Fechatour          time.Time      `json:"fechatour"`
	Preciounitario     string         `json:"preciounitario"`
	Fechacreacion      sql.NullTime   `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime   `json:"fechaactualizacion"`
	Nombreestado       string         `json:"nombreestado"`
	Tournombre         string         `json:"tournombre"`
	Horario            string         `json:"horario"`
	Duracion           int32          `json:"duracion"`
	Preciobase         string         `json:"preciobase"`
	Guianombre         string         `json:"guianombre"`
	Guiatelefono       string         `json:"guiatelefono"`
	Chofernombre       string         `json:"chofernombre"`
	Chofertelefono     string         `json:"chofertelefono"`
	Choferlicencia     string         `json:"choferlicencia"`
	Vehiculomatricula  sql.NullString `json:"vehiculomatricula"`
	Vehiculomodelo     sql.NullString `json:"vehiculomodelo"`
	Vehiculocapacidad  sql.NullInt32  `json:"vehiculocapacidad"`
	Ubicacionnombre    string         `json:"ubicacionnombre"`
	Direccion          string         `json:"direccion"`
	Idiomanombre       string         `json:"idiomanombre"`
}

func (q *Queries) GetDetalleReservaByReserva(ctx context.Context, idreserva int32) ([]GetDetalleReservaByReservaRow, error) {
	rows, err := q.db.QueryContext(ctx, getDetalleReservaByReserva, idreserva)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDetalleReservaByReservaRow
	for rows.Next() {
		var i GetDetalleReservaByReservaRow
		if err := rows.Scan(
			&i.Iddetallereserva,
			&i.Idreserva,
			&i.Fechatour,
			&i.Preciounitario,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
			&i.Nombreestado,
			&i.Tournombre,
			&i.Horario,
			&i.Duracion,
			&i.Preciobase,
			&i.Guianombre,
			&i.Guiatelefono,
			&i.Chofernombre,
			&i.Chofertelefono,
			&i.Choferlicencia,
			&i.Vehiculomatricula,
			&i.Vehiculomodelo,
			&i.Vehiculocapacidad,
			&i.Ubicacionnombre,
			&i.Direccion,
			&i.Idiomanombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDetalleReserva = `-- name: UpdateDetalleReserva :execresult
UPDATE DetalleReserva
SET idTour             = ?,
    idGuia             = ?,
    idChofer           = ?,
    idUbicacion        = ?,
    idIdioma           = ?,
    fechaTour          = ?,
    precioUnitario     = ?,
    fechaActualizacion = now()
WHERE idDetalleReserva = ?
`

type UpdateDetalleReservaParams struct {
	Idtour           int32     `json:"idtour"`
	Idguia           int32     `json:"idguia"`
	Idchofer         int32     `json:"idchofer"`
	Idubicacion      int32     `json:"idubicacion"`
	Ididioma         int32     `json:"ididioma"`
	Fechatour        time.Time `json:"fechatour"`
	Preciounitario   string    `json:"preciounitario"`
	Iddetallereserva int32     `json:"iddetallereserva"`
}

func (q *Queries) UpdateDetalleReserva(ctx context.Context, arg UpdateDetalleReservaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateDetalleReserva,
		arg.Idtour,
		arg.Idguia,
		arg.Idchofer,
		arg.Idubicacion,
		arg.Ididioma,
		arg.Fechatour,
		arg.Preciounitario,
		arg.Iddetallereserva,
	)
}
