// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emailcliente.sql

package dto

import (
	"context"
	"database/sql"
)

const createEmailCliente = `-- name: CreateEmailCliente :execresult
INSERT INTO emailcliente (email, idCliente, fechaCreacion, fechaActualizacion)
VALUES (?, ?, now(), now())
`

type CreateEmailClienteParams struct {
	Email     string `json:"email"`
	Idcliente int32  `json:"idcliente"`
}

func (q *Queries) CreateEmailCliente(ctx context.Context, arg CreateEmailClienteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEmailCliente, arg.Email, arg.Idcliente)
}

const deleteEmailCliente = `-- name: DeleteEmailCliente :execresult
DELETE FROM emailcliente WHERE idEmailCliente = ?
`

func (q *Queries) DeleteEmailCliente(ctx context.Context, idemailcliente int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEmailCliente, idemailcliente)
}

const getAllEmailCliente = `-- name: GetAllEmailCliente :many
SELECT idemailcliente, email, idcliente, fechacreacion, fechaactualizacion FROM emailcliente
`

func (q *Queries) GetAllEmailCliente(ctx context.Context) ([]Emailcliente, error) {
	rows, err := q.db.QueryContext(ctx, getAllEmailCliente)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Emailcliente
	for rows.Next() {
		var i Emailcliente
		if err := rows.Scan(
			&i.Idemailcliente,
			&i.Email,
			&i.Idcliente,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailClienteById = `-- name: GetEmailClienteById :one
SELECT idemailcliente, email, idcliente, fechacreacion, fechaactualizacion FROM emailcliente WHERE idEmailCliente = ?
`

func (q *Queries) GetEmailClienteById(ctx context.Context, idemailcliente int32) (Emailcliente, error) {
	row := q.db.QueryRowContext(ctx, getEmailClienteById, idemailcliente)
	var i Emailcliente
	err := row.Scan(
		&i.Idemailcliente,
		&i.Email,
		&i.Idcliente,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const updateEmailCliente = `-- name: UpdateEmailCliente :execresult
UPDATE emailcliente 
SET email = ?, 
    idCliente = ?,
    fechaActualizacion = now()
WHERE idEmailCliente = ?
`

type UpdateEmailClienteParams struct {
	Email          string `json:"email"`
	Idcliente      int32  `json:"idcliente"`
	Idemailcliente int32  `json:"idemailcliente"`
}

func (q *Queries) UpdateEmailCliente(ctx context.Context, arg UpdateEmailClienteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEmailCliente, arg.Email, arg.Idcliente, arg.Idemailcliente)
}
