// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: empresacliente.sql

package dto

import (
	"context"
	"database/sql"
)

const createEmpresaCliente = `-- name: CreateEmpresaCliente :execresult
INSERT INTO EmpresaCliente (
    razonSocial,
    cedulaJuridica,
    telefono,
    email,
    fechaCreacion,
    fechaActualizacion
)
VALUES (?, ?, ?, ?, now(), now())
`

type CreateEmpresaClienteParams struct {
	Razonsocial    string         `json:"razonsocial"`
	Cedulajuridica string         `json:"cedulajuridica"`
	Telefono       sql.NullString `json:"telefono"`
	Email          string         `json:"email"`
}

func (q *Queries) CreateEmpresaCliente(ctx context.Context, arg CreateEmpresaClienteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEmpresaCliente,
		arg.Razonsocial,
		arg.Cedulajuridica,
		arg.Telefono,
		arg.Email,
	)
}

const deleteEmpresaCliente = `-- name: DeleteEmpresaCliente :execresult
DELETE FROM EmpresaCliente WHERE idEmpresaCliente = ?
`

func (q *Queries) DeleteEmpresaCliente(ctx context.Context, idempresacliente int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEmpresaCliente, idempresacliente)
}

const getAllEmpresaCliente = `-- name: GetAllEmpresaCliente :many
SELECT
    ec.idEmpresaCliente,
    ec.razonSocial,
    ec.cedulaJuridica,
    ec.telefono,
    ec.email,
    ec.fechaCreacion,
    ec.fechaActualizacion,

    -- Cantidad de clientes asociados a la empresa
    COUNT(c.idCliente) AS totalClientes

FROM EmpresaCliente ec

LEFT JOIN Cliente c ON ec.idEmpresaCliente = c.idEmpresaCliente

GROUP BY
    ec.idEmpresaCliente,
    ec.razonSocial,
    ec.cedulaJuridica,
    ec.telefono,
    ec.email,
    ec.fechaCreacion,
    ec.fechaActualizacion
`

type GetAllEmpresaClienteRow struct {
	Idempresacliente   int32          `json:"idempresacliente"`
	Razonsocial        string         `json:"razonsocial"`
	Cedulajuridica     string         `json:"cedulajuridica"`
	Telefono           sql.NullString `json:"telefono"`
	Email              string         `json:"email"`
	Fechacreacion      sql.NullTime   `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime   `json:"fechaactualizacion"`
	Totalclientes      int64          `json:"totalclientes"`
}

func (q *Queries) GetAllEmpresaCliente(ctx context.Context) ([]GetAllEmpresaClienteRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEmpresaCliente)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEmpresaClienteRow
	for rows.Next() {
		var i GetAllEmpresaClienteRow
		if err := rows.Scan(
			&i.Idempresacliente,
			&i.Razonsocial,
			&i.Cedulajuridica,
			&i.Telefono,
			&i.Email,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
			&i.Totalclientes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmpresaClienteByCedula = `-- name: GetEmpresaClienteByCedula :one
SELECT
    ec.idEmpresaCliente,
    ec.razonSocial,
    ec.cedulaJuridica,
    ec.telefono,
    ec.email,
    ec.fechaCreacion,
    ec.fechaActualizacion,

    COUNT(c.idCliente) AS totalClientes

FROM EmpresaCliente ec

LEFT JOIN Cliente c ON ec.idEmpresaCliente = c.idEmpresaCliente

WHERE ec.cedulaJuridica = ?

GROUP BY
    ec.idEmpresaCliente,
    ec.razonSocial,
    ec.cedulaJuridica,
    ec.telefono,
    ec.email,
    ec.fechaCreacion,
    ec.fechaActualizacion
`

type GetEmpresaClienteByCedulaRow struct {
	Idempresacliente   int32          `json:"idempresacliente"`
	Razonsocial        string         `json:"razonsocial"`
	Cedulajuridica     string         `json:"cedulajuridica"`
	Telefono           sql.NullString `json:"telefono"`
	Email              string         `json:"email"`
	Fechacreacion      sql.NullTime   `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime   `json:"fechaactualizacion"`
	Totalclientes      int64          `json:"totalclientes"`
}

func (q *Queries) GetEmpresaClienteByCedula(ctx context.Context, cedulajuridica string) (GetEmpresaClienteByCedulaRow, error) {
	row := q.db.QueryRowContext(ctx, getEmpresaClienteByCedula, cedulajuridica)
	var i GetEmpresaClienteByCedulaRow
	err := row.Scan(
		&i.Idempresacliente,
		&i.Razonsocial,
		&i.Cedulajuridica,
		&i.Telefono,
		&i.Email,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
		&i.Totalclientes,
	)
	return i, err
}

const getEmpresaClienteById = `-- name: GetEmpresaClienteById :one
SELECT
    ec.idEmpresaCliente,
    ec.razonSocial,
    ec.cedulaJuridica,
    ec.telefono,
    ec.email,
    ec.fechaCreacion,
    ec.fechaActualizacion,

    COUNT(c.idCliente) AS totalClientes

FROM EmpresaCliente ec

LEFT JOIN Cliente c ON ec.idEmpresaCliente = c.idEmpresaCliente

WHERE ec.idEmpresaCliente = ?

GROUP BY
    ec.idEmpresaCliente,
    ec.razonSocial,
    ec.cedulaJuridica,
    ec.telefono,
    ec.email,
    ec.fechaCreacion,
    ec.fechaActualizacion
`

type GetEmpresaClienteByIdRow struct {
	Idempresacliente   int32          `json:"idempresacliente"`
	Razonsocial        string         `json:"razonsocial"`
	Cedulajuridica     string         `json:"cedulajuridica"`
	Telefono           sql.NullString `json:"telefono"`
	Email              string         `json:"email"`
	Fechacreacion      sql.NullTime   `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime   `json:"fechaactualizacion"`
	Totalclientes      int64          `json:"totalclientes"`
}

func (q *Queries) GetEmpresaClienteById(ctx context.Context, idempresacliente int32) (GetEmpresaClienteByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getEmpresaClienteById, idempresacliente)
	var i GetEmpresaClienteByIdRow
	err := row.Scan(
		&i.Idempresacliente,
		&i.Razonsocial,
		&i.Cedulajuridica,
		&i.Telefono,
		&i.Email,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
		&i.Totalclientes,
	)
	return i, err
}

const updateEmpresaCliente = `-- name: UpdateEmpresaCliente :execresult
UPDATE EmpresaCliente
SET razonSocial        = ?,
    cedulaJuridica     = ?,
    telefono           = ?,
    email              = ?,
    fechaActualizacion = now()
WHERE idEmpresaCliente = ?
`

type UpdateEmpresaClienteParams struct {
	Razonsocial      string         `json:"razonsocial"`
	Cedulajuridica   string         `json:"cedulajuridica"`
	Telefono         sql.NullString `json:"telefono"`
	Email            string         `json:"email"`
	Idempresacliente int32          `json:"idempresacliente"`
}

func (q *Queries) UpdateEmpresaCliente(ctx context.Context, arg UpdateEmpresaClienteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEmpresaCliente,
		arg.Razonsocial,
		arg.Cedulajuridica,
		arg.Telefono,
		arg.Email,
		arg.Idempresacliente,
	)
}
