// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: estadoreserva.sql

package dto

import (
	"context"
	"database/sql"
)

const createEstadoReserva = `-- name: CreateEstadoReserva :execresult
INSERT INTO EstadoReserva (nombre, descripcion, fechaCreacion, fechaActualizacion)
VALUES (?, ?, now(), now())
`

type CreateEstadoReservaParams struct {
	Nombre      string         `json:"nombre"`
	Descripcion sql.NullString `json:"descripcion"`
}

func (q *Queries) CreateEstadoReserva(ctx context.Context, arg CreateEstadoReservaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEstadoReserva, arg.Nombre, arg.Descripcion)
}

const deleteEstadoReserva = `-- name: DeleteEstadoReserva :execresult
DELETE FROM EstadoReserva WHERE idEstadoReserva = ?
`

func (q *Queries) DeleteEstadoReserva(ctx context.Context, idestadoreserva int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEstadoReserva, idestadoreserva)
}

const getAllEstadoReserva = `-- name: GetAllEstadoReserva :many
SELECT idestadoreserva, nombre, descripcion, fechacreacion, fechaactualizacion FROM EstadoReserva
`

func (q *Queries) GetAllEstadoReserva(ctx context.Context) ([]Estadoreserva, error) {
	rows, err := q.db.QueryContext(ctx, getAllEstadoReserva)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Estadoreserva
	for rows.Next() {
		var i Estadoreserva
		if err := rows.Scan(
			&i.Idestadoreserva,
			&i.Nombre,
			&i.Descripcion,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEstadoReservaById = `-- name: GetEstadoReservaById :one
SELECT idestadoreserva, nombre, descripcion, fechacreacion, fechaactualizacion FROM EstadoReserva WHERE idEstadoReserva = ?
`

func (q *Queries) GetEstadoReservaById(ctx context.Context, idestadoreserva int32) (Estadoreserva, error) {
	row := q.db.QueryRowContext(ctx, getEstadoReservaById, idestadoreserva)
	var i Estadoreserva
	err := row.Scan(
		&i.Idestadoreserva,
		&i.Nombre,
		&i.Descripcion,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const updateEstadoReserva = `-- name: UpdateEstadoReserva :execresult
UPDATE EstadoReserva
SET nombre = ?,
    descripcion = ?,
    fechaActualizacion = now()
WHERE idEstadoReserva = ?
`

type UpdateEstadoReservaParams struct {
	Nombre          string         `json:"nombre"`
	Descripcion     sql.NullString `json:"descripcion"`
	Idestadoreserva int32          `json:"idestadoreserva"`
}

func (q *Queries) UpdateEstadoReserva(ctx context.Context, arg UpdateEstadoReservaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEstadoReserva, arg.Nombre, arg.Descripcion, arg.Idestadoreserva)
}
