// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: estadopago.sql

package dto

import (
	"context"
	"database/sql"
)

const createEstadoPago = `-- name: CreateEstadoPago :execresult
INSERT INTO EstadoPago (nombre, descripcion, fechaCreacion, fechaActualizacion)
VALUES (?, ?, now(), now())
`

type CreateEstadoPagoParams struct {
	Nombre      string         `json:"nombre"`
	Descripcion sql.NullString `json:"descripcion"`
}

func (q *Queries) CreateEstadoPago(ctx context.Context, arg CreateEstadoPagoParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEstadoPago, arg.Nombre, arg.Descripcion)
}

const deleteEstadoPago = `-- name: DeleteEstadoPago :execresult
DELETE FROM EstadoPago WHERE idEstadoPago = ?
`

func (q *Queries) DeleteEstadoPago(ctx context.Context, idestadopago int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEstadoPago, idestadopago)
}

const getAllEstadoPago = `-- name: GetAllEstadoPago :many
SELECT idestadopago, nombre, descripcion, fechacreacion, fechaactualizacion FROM EstadoPago
`

func (q *Queries) GetAllEstadoPago(ctx context.Context) ([]Estadopago, error) {
	rows, err := q.db.QueryContext(ctx, getAllEstadoPago)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Estadopago
	for rows.Next() {
		var i Estadopago
		if err := rows.Scan(
			&i.Idestadopago,
			&i.Nombre,
			&i.Descripcion,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEstadoPagoById = `-- name: GetEstadoPagoById :one
SELECT idestadopago, nombre, descripcion, fechacreacion, fechaactualizacion FROM EstadoPago WHERE idEstadoPago = ?
`

func (q *Queries) GetEstadoPagoById(ctx context.Context, idestadopago int32) (Estadopago, error) {
	row := q.db.QueryRowContext(ctx, getEstadoPagoById, idestadopago)
	var i Estadopago
	err := row.Scan(
		&i.Idestadopago,
		&i.Nombre,
		&i.Descripcion,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const updateEstadoPago = `-- name: UpdateEstadoPago :execresult
UPDATE EstadoPago
SET nombre = ?,
    descripcion = ?,
    fechaActualizacion = now()
WHERE idEstadoPago = ?
`

type UpdateEstadoPagoParams struct {
	Nombre       string         `json:"nombre"`
	Descripcion  sql.NullString `json:"descripcion"`
	Idestadopago int32          `json:"idestadopago"`
}

func (q *Queries) UpdateEstadoPago(ctx context.Context, arg UpdateEstadoPagoParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEstadoPago, arg.Nombre, arg.Descripcion, arg.Idestadopago)
}
