// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: factura.sql

package dto

import (
	"context"
	"database/sql"
	"time"
)

const createFactura = `-- name: CreateFactura :execresult
INSERT INTO Factura (
    idEstadoPago,
    numeroFactura,
    fechaFactura,
    metodoPago,
    moneda,
    fechaPago,
    subtotal,
    impuesto,
    descuento,
    precioTotal,
    fechaCreacion,
    fechaActualizacion
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, now(), now())
`

type CreateFacturaParams struct {
	Idestadopago  int32        `json:"idestadopago"`
	Numerofactura string       `json:"numerofactura"`
	Fechafactura  time.Time    `json:"fechafactura"`
	Metodopago    string       `json:"metodopago"`
	Moneda        string       `json:"moneda"`
	Fechapago     sql.NullTime `json:"fechapago"`
	Subtotal      string       `json:"subtotal"`
	Impuesto      string       `json:"impuesto"`
	Descuento     string       `json:"descuento"`
	Preciototal   string       `json:"preciototal"`
}

func (q *Queries) CreateFactura(ctx context.Context, arg CreateFacturaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFactura,
		arg.Idestadopago,
		arg.Numerofactura,
		arg.Fechafactura,
		arg.Metodopago,
		arg.Moneda,
		arg.Fechapago,
		arg.Subtotal,
		arg.Impuesto,
		arg.Descuento,
		arg.Preciototal,
	)
}

const deleteFactura = `-- name: DeleteFactura :execresult
DELETE FROM Factura WHERE idFactura = ?
`

func (q *Queries) DeleteFactura(ctx context.Context, idfactura int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteFactura, idfactura)
}

const getAllFactura = `-- name: GetAllFactura :many
SELECT
    f.idFactura,
    f.numeroFactura,
    f.fechaFactura,
    f.metodoPago,
    f.moneda,
    f.fechaPago,
    f.subtotal,
    f.impuesto,
    f.descuento,
    f.precioTotal,
    f.fechaCreacion,
    f.fechaActualizacion,

    COUNT(fp.idParticipante) AS cantidadPersonas,

    GROUP_CONCAT(c.nombre ORDER BY c.nombre SEPARATOR ', ') AS clientesNombre,
    GROUP_CONCAT(c.telefono ORDER BY c.nombre SEPARATOR ', ') AS clientesTelefono,

    MAX(t.nombre) AS tourNombre,
    e.nombre AS nombreEstado

FROM Factura f
JOIN FacturaParticipante fp ON fp.idFactura     = f.idFactura
JOIN Participante        p  ON p.idParticipante = fp.idParticipante
JOIN Cliente             c  ON c.idCliente      = p.idCliente
JOIN EstadoPago          e  ON e.idEstadoPago   = f.idEstadoPago
JOIN DetalleReserva      dr ON dr.idReserva     = p.idReserva
JOIN Tour                t  ON t.idTour         = dr.idTour
GROUP BY
    f.idFactura,
    f.numeroFactura,
    f.fechaFactura,
    f.metodoPago,
    f.moneda,
    f.fechaPago,
    f.subtotal,
    f.impuesto,
    f.descuento,
    f.precioTotal,
    f.fechaCreacion,
    f.fechaActualizacion,
    e.nombre
`

type GetAllFacturaRow struct {
	Idfactura          int32          `json:"idfactura"`
	Numerofactura      string         `json:"numerofactura"`
	Fechafactura       time.Time      `json:"fechafactura"`
	Metodopago         string         `json:"metodopago"`
	Moneda             string         `json:"moneda"`
	Fechapago          sql.NullTime   `json:"fechapago"`
	Subtotal           string         `json:"subtotal"`
	Impuesto           string         `json:"impuesto"`
	Descuento          string         `json:"descuento"`
	Preciototal        string         `json:"preciototal"`
	Fechacreacion      sql.NullTime   `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime   `json:"fechaactualizacion"`
	Cantidadpersonas   int64          `json:"cantidadpersonas"`
	Clientesnombre     sql.NullString `json:"clientesnombre"`
	Clientestelefono   sql.NullString `json:"clientestelefono"`
	Tournombre         interface{}    `json:"tournombre"`
	Nombreestado       string         `json:"nombreestado"`
}

func (q *Queries) GetAllFactura(ctx context.Context) ([]GetAllFacturaRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFactura)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFacturaRow
	for rows.Next() {
		var i GetAllFacturaRow
		if err := rows.Scan(
			&i.Idfactura,
			&i.Numerofactura,
			&i.Fechafactura,
			&i.Metodopago,
			&i.Moneda,
			&i.Fechapago,
			&i.Subtotal,
			&i.Impuesto,
			&i.Descuento,
			&i.Preciototal,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
			&i.Cantidadpersonas,
			&i.Clientesnombre,
			&i.Clientestelefono,
			&i.Tournombre,
			&i.Nombreestado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFacturaById = `-- name: GetFacturaById :one
SELECT
    f.idFactura,
    f.numeroFactura,
    f.fechaFactura,
    f.metodoPago,
    f.moneda,
    f.fechaPago,
    f.subtotal,
    f.impuesto,
    f.descuento,
    f.precioTotal,
    f.fechaCreacion,
    f.fechaActualizacion,

    COUNT(fp.idParticipante) AS cantidadPersonas,
    GROUP_CONCAT(c.nombre ORDER BY c.nombre SEPARATOR ', ') AS clientesNombre,
    GROUP_CONCAT(c.telefono ORDER BY c.nombre SEPARATOR ', ') AS clientesTelefono,

    MAX(t.nombre) AS tourNombre,
    e.nombre AS nombreEstado

FROM Factura f
JOIN FacturaParticipante fp ON fp.idFactura     = f.idFactura
JOIN Participante        p  ON p.idParticipante = fp.idParticipante
JOIN Cliente             c  ON c.idCliente      = p.idCliente
JOIN EstadoPago          e  ON e.idEstadoPago   = f.idEstadoPago
JOIN DetalleReserva      dr ON dr.idReserva     = p.idReserva
JOIN Tour                t  ON t.idTour         = dr.idTour
WHERE f.idFactura = ?
GROUP BY
    f.idFactura,
    f.numeroFactura,
    f.fechaFactura,
    f.metodoPago,
    f.moneda,
    f.fechaPago,
    f.subtotal,
    f.impuesto,
    f.descuento,
    f.precioTotal,
    f.fechaCreacion,
    f.fechaActualizacion,
    e.nombre
`

type GetFacturaByIdRow struct {
	Idfactura          int32          `json:"idfactura"`
	Numerofactura      string         `json:"numerofactura"`
	Fechafactura       time.Time      `json:"fechafactura"`
	Metodopago         string         `json:"metodopago"`
	Moneda             string         `json:"moneda"`
	Fechapago          sql.NullTime   `json:"fechapago"`
	Subtotal           string         `json:"subtotal"`
	Impuesto           string         `json:"impuesto"`
	Descuento          string         `json:"descuento"`
	Preciototal        string         `json:"preciototal"`
	Fechacreacion      sql.NullTime   `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime   `json:"fechaactualizacion"`
	Cantidadpersonas   int64          `json:"cantidadpersonas"`
	Clientesnombre     sql.NullString `json:"clientesnombre"`
	Clientestelefono   sql.NullString `json:"clientestelefono"`
	Tournombre         interface{}    `json:"tournombre"`
	Nombreestado       string         `json:"nombreestado"`
}

func (q *Queries) GetFacturaById(ctx context.Context, idfactura int32) (GetFacturaByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getFacturaById, idfactura)
	var i GetFacturaByIdRow
	err := row.Scan(
		&i.Idfactura,
		&i.Numerofactura,
		&i.Fechafactura,
		&i.Metodopago,
		&i.Moneda,
		&i.Fechapago,
		&i.Subtotal,
		&i.Impuesto,
		&i.Descuento,
		&i.Preciototal,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
		&i.Cantidadpersonas,
		&i.Clientesnombre,
		&i.Clientestelefono,
		&i.Tournombre,
		&i.Nombreestado,
	)
	return i, err
}

const getParticiapntesSinFactura = `-- name: GetParticiapntesSinFactura :many
SELECT p.idParticipante, c.nombre
FROM Participante p
JOIN Cliente c ON p.idCliente = c.idCliente
LEFT JOIN FacturaParticipante fp ON p.idParticipante = fp.idParticipante
WHERE p.idReserva = ?
AND fp.idParticipante IS NULL
`

type GetParticiapntesSinFacturaRow struct {
	Idparticipante int32  `json:"idparticipante"`
	Nombre         string `json:"nombre"`
}

func (q *Queries) GetParticiapntesSinFactura(ctx context.Context, idreserva int32) ([]GetParticiapntesSinFacturaRow, error) {
	rows, err := q.db.QueryContext(ctx, getParticiapntesSinFactura, idreserva)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetParticiapntesSinFacturaRow
	for rows.Next() {
		var i GetParticiapntesSinFacturaRow
		if err := rows.Scan(&i.Idparticipante, &i.Nombre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservasDisponiblesParaFacturar = `-- name: GetReservasDisponiblesParaFacturar :many
SELECT
    r.idReserva,
    r.idEstadoReserva,
    r.fechaCreacion,
    r.fechaActualizacion,
    dr.precioUnitario,
    GROUP_CONCAT(DISTINCT c.nombre ORDER BY c.nombre SEPARATOR ', ') AS clientenombres
FROM Reserva r
JOIN Participante p ON p.idReserva = r.idReserva
JOIN Cliente c ON c.idCliente = p.idCliente
JOIN DetalleReserva dr ON dr.idReserva = r.idReserva
LEFT JOIN FacturaParticipante fp ON fp.idParticipante = p.idParticipante
GROUP BY
    r.idReserva,
    r.idEstadoReserva,
    r.fechaCreacion,
    r.fechaActualizacion,
    dr.precioUnitario
HAVING SUM(CASE WHEN fp.idParticipante IS NULL THEN 1 ELSE 0 END) > 0
`

type GetReservasDisponiblesParaFacturarRow struct {
	Idreserva          int32          `json:"idreserva"`
	Idestadoreserva    int32          `json:"idestadoreserva"`
	Fechacreacion      sql.NullTime   `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime   `json:"fechaactualizacion"`
	Preciounitario     string         `json:"preciounitario"`
	Clientenombres     sql.NullString `json:"clientenombres"`
}

func (q *Queries) GetReservasDisponiblesParaFacturar(ctx context.Context) ([]GetReservasDisponiblesParaFacturarRow, error) {
	rows, err := q.db.QueryContext(ctx, getReservasDisponiblesParaFacturar)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReservasDisponiblesParaFacturarRow
	for rows.Next() {
		var i GetReservasDisponiblesParaFacturarRow
		if err := rows.Scan(
			&i.Idreserva,
			&i.Idestadoreserva,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
			&i.Preciounitario,
			&i.Clientenombres,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFactura = `-- name: UpdateFactura :execresult
UPDATE Factura
SET idEstadoPago       = ?,
    numeroFactura      = ?,
    fechaFactura       = ?,
    metodoPago         = ?,
    moneda             = ?,
    fechaPago          = ?,
    subtotal           = ?,
    impuesto           = ?,
    descuento          = ?,
    precioTotal        = ?,
    fechaActualizacion = now()
WHERE idFactura = ?
`

type UpdateFacturaParams struct {
	Idestadopago  int32        `json:"idestadopago"`
	Numerofactura string       `json:"numerofactura"`
	Fechafactura  time.Time    `json:"fechafactura"`
	Metodopago    string       `json:"metodopago"`
	Moneda        string       `json:"moneda"`
	Fechapago     sql.NullTime `json:"fechapago"`
	Subtotal      string       `json:"subtotal"`
	Impuesto      string       `json:"impuesto"`
	Descuento     string       `json:"descuento"`
	Preciototal   string       `json:"preciototal"`
	Idfactura     int32        `json:"idfactura"`
}

func (q *Queries) UpdateFactura(ctx context.Context, arg UpdateFacturaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateFactura,
		arg.Idestadopago,
		arg.Numerofactura,
		arg.Fechafactura,
		arg.Metodopago,
		arg.Moneda,
		arg.Fechapago,
		arg.Subtotal,
		arg.Impuesto,
		arg.Descuento,
		arg.Preciototal,
		arg.Idfactura,
	)
}
