// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: factura.sql

package dto

import (
	"context"
	"database/sql"
	"time"
)

const createFactura = `-- name: CreateFactura :execresult
INSERT INTO Factura (
    idParticipante,
    idEstadoPago,
    numeroFactura,
    fechaFactura,
    metodoPago,
    moneda,
    fechaPago,
    subtotal,
    impuesto,
    descuento,
    precioTotal,
    fechaCreacion,
    fechaActualizacion
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, now(), now())
`

type CreateFacturaParams struct {
	Idparticipante int32        `json:"idparticipante"`
	Idestadopago   int32        `json:"idestadopago"`
	Numerofactura  string       `json:"numerofactura"`
	Fechafactura   time.Time    `json:"fechafactura"`
	Metodopago     string       `json:"metodopago"`
	Moneda         string       `json:"moneda"`
	Fechapago      sql.NullTime `json:"fechapago"`
	Subtotal       string       `json:"subtotal"`
	Impuesto       string       `json:"impuesto"`
	Descuento      string       `json:"descuento"`
	Preciototal    string       `json:"preciototal"`
}

func (q *Queries) CreateFactura(ctx context.Context, arg CreateFacturaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFactura,
		arg.Idparticipante,
		arg.Idestadopago,
		arg.Numerofactura,
		arg.Fechafactura,
		arg.Metodopago,
		arg.Moneda,
		arg.Fechapago,
		arg.Subtotal,
		arg.Impuesto,
		arg.Descuento,
		arg.Preciototal,
	)
}

const deleteFactura = `-- name: DeleteFactura :execresult
DELETE FROM Factura WHERE idFactura = ?
`

func (q *Queries) DeleteFactura(ctx context.Context, idfactura int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteFactura, idfactura)
}

const getAllFactura = `-- name: GetAllFactura :many
SELECT 
    f.idFactura,
    f.numeroFactura,
    f.fechaFactura,
    f.metodoPago,
    f.moneda,
    f.fechaPago,
    f.subtotal,
    f.impuesto,
    f.descuento,
    f.precioTotal,
    f.fechaCreacion,
    f.fechaActualizacion,

    -- Cantidad de participantes de la reserva
    (SELECT COUNT(*) 
     FROM Participante p2 
     WHERE p2.idReserva = p.idReserva) AS cantidadPersonas,

    -- Cliente dueño de esta factura
    c.nombre AS clienteNombre,
    c.telefono AS clienteTelefono,

    -- Tour: primer detalle de la reserva
    (SELECT t.nombre 
     FROM DetalleReserva dr 
     JOIN Tour t ON t.idTour = dr.idTour 
     WHERE dr.idReserva = p.idReserva 
     LIMIT 1) AS tourNombre,

    -- Estado Pago
    e.nombre AS nombreEstado

FROM Factura f
JOIN Participante p ON f.idParticipante = p.idParticipante
JOIN Cliente c ON p.idCliente = c.idCliente
JOIN EstadoPago e ON f.idEstadoPago = e.idEstadoPago
`

type GetAllFacturaRow struct {
	Idfactura          int32        `json:"idfactura"`
	Numerofactura      string       `json:"numerofactura"`
	Fechafactura       time.Time    `json:"fechafactura"`
	Metodopago         string       `json:"metodopago"`
	Moneda             string       `json:"moneda"`
	Fechapago          sql.NullTime `json:"fechapago"`
	Subtotal           string       `json:"subtotal"`
	Impuesto           string       `json:"impuesto"`
	Descuento          string       `json:"descuento"`
	Preciototal        string       `json:"preciototal"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
	Cantidadpersonas   int64        `json:"cantidadpersonas"`
	Clientenombre      string       `json:"clientenombre"`
	Clientetelefono    string       `json:"clientetelefono"`
	Tournombre         string       `json:"tournombre"`
	Nombreestado       string       `json:"nombreestado"`
}

func (q *Queries) GetAllFactura(ctx context.Context) ([]GetAllFacturaRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFactura)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFacturaRow
	for rows.Next() {
		var i GetAllFacturaRow
		if err := rows.Scan(
			&i.Idfactura,
			&i.Numerofactura,
			&i.Fechafactura,
			&i.Metodopago,
			&i.Moneda,
			&i.Fechapago,
			&i.Subtotal,
			&i.Impuesto,
			&i.Descuento,
			&i.Preciototal,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
			&i.Cantidadpersonas,
			&i.Clientenombre,
			&i.Clientetelefono,
			&i.Tournombre,
			&i.Nombreestado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFacturaById = `-- name: GetFacturaById :one
SELECT idfactura, idparticipante, idestadopago, numerofactura, fechafactura, metodopago, moneda, fechapago, subtotal, descuento, impuesto, preciototal, fechacreacion, fechaactualizacion FROM Factura WHERE idFactura = ?
`

func (q *Queries) GetFacturaById(ctx context.Context, idfactura int32) (Factura, error) {
	row := q.db.QueryRowContext(ctx, getFacturaById, idfactura)
	var i Factura
	err := row.Scan(
		&i.Idfactura,
		&i.Idparticipante,
		&i.Idestadopago,
		&i.Numerofactura,
		&i.Fechafactura,
		&i.Metodopago,
		&i.Moneda,
		&i.Fechapago,
		&i.Subtotal,
		&i.Descuento,
		&i.Impuesto,
		&i.Preciototal,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const updateFactura = `-- name: UpdateFactura :execresult
UPDATE Factura
SET idParticipante = ?,
    idEstadoPago = ?,
    numeroFactura = ?,
    fechaFactura = ?,
    metodoPago = ?,
    moneda = ?,
    fechaPago = ?,
    subtotal = ?,
    impuesto = ?,
    descuento = ?,
    precioTotal = ?,
    fechaActualizacion = now()
WHERE idFactura = ?
`

type UpdateFacturaParams struct {
	Idparticipante int32        `json:"idparticipante"`
	Idestadopago   int32        `json:"idestadopago"`
	Numerofactura  string       `json:"numerofactura"`
	Fechafactura   time.Time    `json:"fechafactura"`
	Metodopago     string       `json:"metodopago"`
	Moneda         string       `json:"moneda"`
	Fechapago      sql.NullTime `json:"fechapago"`
	Subtotal       string       `json:"subtotal"`
	Impuesto       string       `json:"impuesto"`
	Descuento      string       `json:"descuento"`
	Preciototal    string       `json:"preciototal"`
	Idfactura      int32        `json:"idfactura"`
}

func (q *Queries) UpdateFactura(ctx context.Context, arg UpdateFacturaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateFactura,
		arg.Idparticipante,
		arg.Idestadopago,
		arg.Numerofactura,
		arg.Fechafactura,
		arg.Metodopago,
		arg.Moneda,
		arg.Fechapago,
		arg.Subtotal,
		arg.Impuesto,
		arg.Descuento,
		arg.Preciototal,
		arg.Idfactura,
	)
}
