// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: facturaparticipante.sql

package dto

import (
	"context"
	"database/sql"
)

const createFacturaParticipante = `-- name: CreateFacturaParticipante :execresult
INSERT INTO FacturaParticipante (
    idFactura,
    idParticipante,
    fechaCreacion,
    fechaActualizacion
)
VALUES (?, ?, now(), now())
`

type CreateFacturaParticipanteParams struct {
	Idfactura      int32 `json:"idfactura"`
	Idparticipante int32 `json:"idparticipante"`
}

func (q *Queries) CreateFacturaParticipante(ctx context.Context, arg CreateFacturaParticipanteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFacturaParticipante, arg.Idfactura, arg.Idparticipante)
}

const deleteFacturaParticipante = `-- name: DeleteFacturaParticipante :execresult
DELETE FROM FacturaParticipante
WHERE idFacturaParticipante = ?
`

func (q *Queries) DeleteFacturaParticipante(ctx context.Context, idfacturaparticipante int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteFacturaParticipante, idfacturaparticipante)
}

const deleteFacturaParticipanteByFactura = `-- name: DeleteFacturaParticipanteByFactura :execresult
DELETE FROM FacturaParticipante
WHERE idFactura = ?
`

func (q *Queries) DeleteFacturaParticipanteByFactura(ctx context.Context, idfactura int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteFacturaParticipanteByFactura, idfactura)
}

const getFacturaByParticipante = `-- name: GetFacturaByParticipante :one
SELECT
    fp.idFacturaParticipante,
    fp.idFactura,
    fp.idParticipante,
    fp.fechaCreacion,
    fp.fechaActualizacion
FROM FacturaParticipante fp
WHERE fp.idParticipante = ?
`

func (q *Queries) GetFacturaByParticipante(ctx context.Context, idparticipante int32) (Facturaparticipante, error) {
	row := q.db.QueryRowContext(ctx, getFacturaByParticipante, idparticipante)
	var i Facturaparticipante
	err := row.Scan(
		&i.Idfacturaparticipante,
		&i.Idfactura,
		&i.Idparticipante,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const getParticipantesByFactura = `-- name: GetParticipantesByFactura :many
SELECT
    fp.idFacturaParticipante,
    fp.idFactura,
    fp.idParticipante,
    c.nombre      AS clienteNombre,
    c.telefono    AS clienteTelefono,
    c.identificador AS clienteIdentificador,
    fp.fechaCreacion,
    fp.fechaActualizacion
FROM FacturaParticipante fp
JOIN Participante p ON p.idParticipante = fp.idParticipante
JOIN Cliente      c ON c.idCliente      = p.idCliente
WHERE fp.idFactura = ?
`

type GetParticipantesByFacturaRow struct {
	Idfacturaparticipante int32        `json:"idfacturaparticipante"`
	Idfactura             int32        `json:"idfactura"`
	Idparticipante        int32        `json:"idparticipante"`
	Clientenombre         string       `json:"clientenombre"`
	Clientetelefono       string       `json:"clientetelefono"`
	Clienteidentificador  string       `json:"clienteidentificador"`
	Fechacreacion         sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion    sql.NullTime `json:"fechaactualizacion"`
}

func (q *Queries) GetParticipantesByFactura(ctx context.Context, idfactura int32) ([]GetParticipantesByFacturaRow, error) {
	rows, err := q.db.QueryContext(ctx, getParticipantesByFactura, idfactura)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetParticipantesByFacturaRow
	for rows.Next() {
		var i GetParticipantesByFacturaRow
		if err := rows.Scan(
			&i.Idfacturaparticipante,
			&i.Idfactura,
			&i.Idparticipante,
			&i.Clientenombre,
			&i.Clientetelefono,
			&i.Clienteidentificador,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFacturaParticipante = `-- name: UpdateFacturaParticipante :execresult
UPDATE FacturaParticipante
SET idFactura          = ?,
    fechaActualizacion = now()
WHERE idParticipante = ?
`

type UpdateFacturaParticipanteParams struct {
	Idfactura      int32 `json:"idfactura"`
	Idparticipante int32 `json:"idparticipante"`
}

func (q *Queries) UpdateFacturaParticipante(ctx context.Context, arg UpdateFacturaParticipanteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateFacturaParticipante, arg.Idfactura, arg.Idparticipante)
}
