// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guia.sql

package dto

import (
	"context"
	"database/sql"
	"time"
)

const createGuia = `-- name: CreateGuia :execresult
INSERT INTO Guia (nombre, identificador, fechaNac, telefono, nacionalidad, email, fechaCreacion, fechaActualizacion)
VALUES (?, ?, ?, ?, ?, ?, now(), now())
`

type CreateGuiaParams struct {
	Nombre        string    `json:"nombre"`
	Identificador string    `json:"identificador"`
	Fechanac      time.Time `json:"fechanac"`
	Telefono      string    `json:"telefono"`
	Nacionalidad  string    `json:"nacionalidad"`
	Email         string    `json:"email"`
}

func (q *Queries) CreateGuia(ctx context.Context, arg CreateGuiaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGuia,
		arg.Nombre,
		arg.Identificador,
		arg.Fechanac,
		arg.Telefono,
		arg.Nacionalidad,
		arg.Email,
	)
}

const deleteGuia = `-- name: DeleteGuia :execresult
DELETE FROM Guia WHERE idGuia = ?
`

func (q *Queries) DeleteGuia(ctx context.Context, idguia int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteGuia, idguia)
}

const getAllGuia = `-- name: GetAllGuia :many
SELECT idguia, nombre, identificador, fechanac, telefono, nacionalidad, email, fechacreacion, fechaactualizacion FROM Guia
`

func (q *Queries) GetAllGuia(ctx context.Context) ([]Guium, error) {
	rows, err := q.db.QueryContext(ctx, getAllGuia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guium
	for rows.Next() {
		var i Guium
		if err := rows.Scan(
			&i.Idguia,
			&i.Nombre,
			&i.Identificador,
			&i.Fechanac,
			&i.Telefono,
			&i.Nacionalidad,
			&i.Email,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGuiaById = `-- name: GetGuiaById :one
SELECT idguia, nombre, identificador, fechanac, telefono, nacionalidad, email, fechacreacion, fechaactualizacion FROM Guia WHERE idGuia = ?
`

func (q *Queries) GetGuiaById(ctx context.Context, idguia int32) (Guium, error) {
	row := q.db.QueryRowContext(ctx, getGuiaById, idguia)
	var i Guium
	err := row.Scan(
		&i.Idguia,
		&i.Nombre,
		&i.Identificador,
		&i.Fechanac,
		&i.Telefono,
		&i.Nacionalidad,
		&i.Email,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const updateGuia = `-- name: UpdateGuia :execresult
UPDATE Guia 
SET nombre = ?,  
    identificador = ?,
    fechaNac = ?,  
    telefono = ?,
    nacionalidad = ?,
    email = ?,
    fechaActualizacion = now()
WHERE idGuia = ?
`

type UpdateGuiaParams struct {
	Nombre        string    `json:"nombre"`
	Identificador string    `json:"identificador"`
	Fechanac      time.Time `json:"fechanac"`
	Telefono      string    `json:"telefono"`
	Nacionalidad  string    `json:"nacionalidad"`
	Email         string    `json:"email"`
	Idguia        int32     `json:"idguia"`
}

func (q *Queries) UpdateGuia(ctx context.Context, arg UpdateGuiaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateGuia,
		arg.Nombre,
		arg.Identificador,
		arg.Fechanac,
		arg.Telefono,
		arg.Nacionalidad,
		arg.Email,
		arg.Idguia,
	)
}
