// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idioma.sql

package dto

import (
	"context"
	"database/sql"
)

const createIdioma = `-- name: CreateIdioma :execresult
INSERT INTO Idioma (nombre, fechaCreacion, fechaActualizacion)
VALUES (?, now(), now())
`

func (q *Queries) CreateIdioma(ctx context.Context, nombre string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createIdioma, nombre)
}

const deleteIdioma = `-- name: DeleteIdioma :execresult
DELETE FROM Idioma WHERE idIdioma = ?
`

func (q *Queries) DeleteIdioma(ctx context.Context, ididioma int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteIdioma, ididioma)
}

const getAllIdioma = `-- name: GetAllIdioma :many
SELECT ididioma, nombre, fechacreacion, fechaactualizacion FROM Idioma
`

func (q *Queries) GetAllIdioma(ctx context.Context) ([]Idioma, error) {
	rows, err := q.db.QueryContext(ctx, getAllIdioma)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Idioma
	for rows.Next() {
		var i Idioma
		if err := rows.Scan(
			&i.Ididioma,
			&i.Nombre,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdiomaById = `-- name: GetIdiomaById :one
SELECT ididioma, nombre, fechacreacion, fechaactualizacion FROM Idioma WHERE idIdioma = ?
`

func (q *Queries) GetIdiomaById(ctx context.Context, ididioma int32) (Idioma, error) {
	row := q.db.QueryRowContext(ctx, getIdiomaById, ididioma)
	var i Idioma
	err := row.Scan(
		&i.Ididioma,
		&i.Nombre,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const updateIdioma = `-- name: UpdateIdioma :execresult
UPDATE Idioma 
SET nombre = ?, 
    fechaActualizacion = now()
WHERE idIdioma = ?
`

type UpdateIdiomaParams struct {
	Nombre   string `json:"nombre"`
	Ididioma int32  `json:"ididioma"`
}

func (q *Queries) UpdateIdioma(ctx context.Context, arg UpdateIdiomaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateIdioma, arg.Nombre, arg.Ididioma)
}
