// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idiomaguia.sql

package dto

import (
	"context"
	"database/sql"
)

const createIdiomaGuia = `-- name: CreateIdiomaGuia :execresult
INSERT INTO IdiomaGuia (idGuia, idIdioma, fechaCreacion, fechaActualizacion)
VALUES (?, ?, now(), now())
`

type CreateIdiomaGuiaParams struct {
	Idguia   int32 `json:"idguia"`
	Ididioma int32 `json:"ididioma"`
}

func (q *Queries) CreateIdiomaGuia(ctx context.Context, arg CreateIdiomaGuiaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createIdiomaGuia, arg.Idguia, arg.Ididioma)
}

const deleteIdiomaGuia = `-- name: DeleteIdiomaGuia :execresult
DELETE FROM IdiomaGuia WHERE idIdiomaGuia = ?
`

func (q *Queries) DeleteIdiomaGuia(ctx context.Context, ididiomaguia int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteIdiomaGuia, ididiomaguia)
}

const getIdiomasByGuia = `-- name: GetIdiomasByGuia :many
SELECT ig.ididiomaguia, ig.idguia, ig.ididioma, i.nombre AS nombreIdioma
FROM IdiomaGuia ig
JOIN Idioma i ON ig.idIdioma = i.idIdioma
WHERE ig.idGuia = ?
`

type GetIdiomasByGuiaRow struct {
	Ididiomaguia int32  `json:"ididiomaguia"`
	Idguia       int32  `json:"idguia"`
	Ididioma     int32  `json:"ididioma"`
	Nombreidioma string `json:"nombreidioma"`
}

func (q *Queries) GetIdiomasByGuia(ctx context.Context, idguia int32) ([]GetIdiomasByGuiaRow, error) {
	rows, err := q.db.QueryContext(ctx, getIdiomasByGuia, idguia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIdiomasByGuiaRow
	for rows.Next() {
		var i GetIdiomasByGuiaRow
		if err := rows.Scan(
			&i.Ididiomaguia,
			&i.Idguia,
			&i.Ididioma,
			&i.Nombreidioma,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
