// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idiomaguia.sql

package dto

import (
	"context"
	"database/sql"
)

const createIdiomaGuia = `-- name: CreateIdiomaGuia :execresult
INSERT INTO idiomaguia (idGuia, idIdioma, fechaCreacion, fechaActualizacion)
VALUES (?, ?, now(), now())
`

type CreateIdiomaGuiaParams struct {
	Idguia   int32 `json:"idguia"`
	Ididioma int32 `json:"ididioma"`
}

func (q *Queries) CreateIdiomaGuia(ctx context.Context, arg CreateIdiomaGuiaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createIdiomaGuia, arg.Idguia, arg.Ididioma)
}

const deleteIdiomaGuia = `-- name: DeleteIdiomaGuia :execresult
DELETE FROM idiomaguia WHERE idIdiomaGuia = ?
`

func (q *Queries) DeleteIdiomaGuia(ctx context.Context, ididiomaguia int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteIdiomaGuia, ididiomaguia)
}

const getAllIdiomaGuia = `-- name: GetAllIdiomaGuia :many
SELECT ididiomaguia, idguia, ididioma, fechacreacion, fechaactualizacion FROM idiomaguia
`

func (q *Queries) GetAllIdiomaGuia(ctx context.Context) ([]Idiomaguium, error) {
	rows, err := q.db.QueryContext(ctx, getAllIdiomaGuia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Idiomaguium
	for rows.Next() {
		var i Idiomaguium
		if err := rows.Scan(
			&i.Ididiomaguia,
			&i.Idguia,
			&i.Ididioma,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdiomaGuiaById = `-- name: GetIdiomaGuiaById :one
SELECT ididiomaguia, idguia, ididioma, fechacreacion, fechaactualizacion FROM idiomaguia WHERE idIdiomaGuia = ?
`

func (q *Queries) GetIdiomaGuiaById(ctx context.Context, ididiomaguia int32) (Idiomaguium, error) {
	row := q.db.QueryRowContext(ctx, getIdiomaGuiaById, ididiomaguia)
	var i Idiomaguium
	err := row.Scan(
		&i.Ididiomaguia,
		&i.Idguia,
		&i.Ididioma,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const updateIdiomaGuia = `-- name: UpdateIdiomaGuia :execresult
UPDATE idiomaguia 
SET idGuia = ?, 
    idIdioma = ?,
    fechaActualizacion = now()
WHERE idIdiomaGuia = ?
`

type UpdateIdiomaGuiaParams struct {
	Idguia       int32 `json:"idguia"`
	Ididioma     int32 `json:"ididioma"`
	Ididiomaguia int32 `json:"ididiomaguia"`
}

func (q *Queries) UpdateIdiomaGuia(ctx context.Context, arg UpdateIdiomaGuiaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateIdiomaGuia, arg.Idguia, arg.Ididioma, arg.Ididiomaguia)
}
