// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dto

import (
	"database/sql"
	"time"
)

type Chofer struct {
	Idchofer           int32        `json:"idchofer"`
	Nombre             string       `json:"nombre"`
	Fechanac           time.Time    `json:"fechanac"`
	Telefono           int32        `json:"telefono"`
	Email              string       `json:"email"`
	Tipolicencia       string       `json:"tipolicencia"`
	Nacionalidad       string       `json:"nacionalidad"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
}

type Cliente struct {
	Idcliente          int32        `json:"idcliente"`
	Nombre             string       `json:"nombre"`
	Telefono           int32        `json:"telefono"`
	Nacionalidad       string       `json:"nacionalidad"`
	Fecharegistro      time.Time    `json:"fecharegistro"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
}

type Clienteemail struct {
	Idemailcliente     int32        `json:"idemailcliente"`
	Email              string       `json:"email"`
	Idcliente          int32        `json:"idcliente"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
}

type Factura struct {
	Idfactura          int32        `json:"idfactura"`
	Idreserva          int32        `json:"idreserva"`
	Numerofactura      string       `json:"numerofactura"`
	Fechafactura       time.Time    `json:"fechafactura"`
	Metodopago         string       `json:"metodopago"`
	Moneda             string       `json:"moneda"`
	Estadopago         string       `json:"estadopago"`
	Fechapago          sql.NullTime `json:"fechapago"`
	Subtotal           string       `json:"subtotal"`
	Impuesto           string       `json:"impuesto"`
	Descuento          string       `json:"descuento"`
	Preciototal        string       `json:"preciototal"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
}

type Guium struct {
	Idguia             int32        `json:"idguia"`
	Nombre             string       `json:"nombre"`
	Fechanac           time.Time    `json:"fechanac"`
	Telefono           int32        `json:"telefono"`
	Nacionalidad       string       `json:"nacionalidad"`
	Email              string       `json:"email"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
}

type Idioma struct {
	Ididioma           int32        `json:"ididioma"`
	Nombre             string       `json:"nombre"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
}

type Idiomaguium struct {
	Ididiomaguia       int32        `json:"ididiomaguia"`
	Idguia             int32        `json:"idguia"`
	Ididioma           int32        `json:"ididioma"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
}

type Participante struct {
	Idparticipante     int32        `json:"idparticipante"`
	Idreserva          int32        `json:"idreserva"`
	Nombre             string       `json:"nombre"`
	Fechanac           time.Time    `json:"fechanac"`
	Nacionalidad       string       `json:"nacionalidad"`
	Telefono           int32        `json:"telefono"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
}

type Reserva struct {
	Idreserva          int32        `json:"idreserva"`
	Idcliente          int32        `json:"idcliente"`
	Idtour             int32        `json:"idtour"`
	Idguia             int32        `json:"idguia"`
	Idtransporte       int32        `json:"idtransporte"`
	Idubicacion        int32        `json:"idubicacion"`
	Ididioma           int32        `json:"ididioma"`
	Cantidadpersonas   int32        `json:"cantidadpersonas"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
}

type Tour struct {
	Idtour             int32        `json:"idtour"`
	Nombre             string       `json:"nombre"`
	Descripcion        string       `json:"descripcion"`
	Horario            string       `json:"horario"`
	Duracion           int32        `json:"duracion"`
	Cuposmaximos       int32        `json:"cuposmaximos"`
	Preciobase         float64      `json:"preciobase"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
}

type Transporte struct {
	Idtransporte       int32        `json:"idtransporte"`
	Idchofer           int32        `json:"idchofer"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
}

type Ubicacion struct {
	Idubicacion        int32        `json:"idubicacion"`
	Nombre             string       `json:"nombre"`
	Direccion          string       `json:"direccion"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
}

type Usuario struct {
	Idusuario          int32          `json:"idusuario"`
	Nombre             string         `json:"nombre"`
	Apellido           sql.NullString `json:"apellido"`
	Rol                sql.NullString `json:"rol"`
	Correo             string         `json:"correo"`
	Contrasena         string         `json:"contrasena"`
	Descripcion        sql.NullString `json:"descripcion"`
	Imagen             sql.NullString `json:"imagen"`
	Fechacreacion      sql.NullTime   `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime   `json:"fechaactualizacion"`
	Tokenrecordar      sql.NullString `json:"tokenrecordar"`
}

type Vehiculo struct {
	Idvehiculo         int32        `json:"idvehiculo"`
	Idchofer           int32        `json:"idchofer"`
	Matricula          string       `json:"matricula"`
	Capacidad          int32        `json:"capacidad"`
	Modelo             string       `json:"modelo"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
}
