// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participante.sql

package dto

import (
	"context"
	"database/sql"
	"time"
)

const createParticipante = `-- name: CreateParticipante :execresult
INSERT INTO Participante (
    idCliente,
    idReserva,
    fechaCreacion,
    fechaActualizacion
)
VALUES (?, ?, now(), now())
`

type CreateParticipanteParams struct {
	Idcliente int32 `json:"idcliente"`
	Idreserva int32 `json:"idreserva"`
}

func (q *Queries) CreateParticipante(ctx context.Context, arg CreateParticipanteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createParticipante, arg.Idcliente, arg.Idreserva)
}

const deleteParticipante = `-- name: DeleteParticipante :execresult
DELETE FROM Participante WHERE idParticipante = ?
`

func (q *Queries) DeleteParticipante(ctx context.Context, idparticipante int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteParticipante, idparticipante)
}

const getAllParticipante = `-- name: GetAllParticipante :many
SELECT
    p.idParticipante,
    p.idCliente,
    p.idReserva,
    p.fechaCreacion,
    p.fechaActualizacion,

    -- Cliente
    c.nombre            AS clienteNombre,
    c.identificador     AS clienteIdentificador,
    c.telefono          AS clienteTelefono,
    c.nacionalidad      AS clienteNacionalidad,
    c.fechaNac          AS clienteFechaNac,

    -- Empresa del cliente (si tiene)
    ec.razonSocial      AS empresaNombre,
    ec.cedulaJuridica   AS empresaCedula,

    -- Reserva
    e.nombre            AS nombreEstado,

    -- Tour asociado a la reserva
    t.nombre            AS tourNombre,
    dr.fechaTour

FROM Participante p

JOIN Cliente c              ON p.idCliente          = c.idCliente
JOIN Reserva r              ON p.idReserva          = r.idReserva
JOIN EstadoReserva e        ON r.idEstadoReserva    = e.idEstadoReserva
JOIN DetalleReserva dr      ON r.idReserva          = dr.idReserva
JOIN Tour t                 ON dr.idTour            = t.idTour
LEFT JOIN EmpresaCliente ec ON c.idEmpresaCliente   = ec.idEmpresaCliente
`

type GetAllParticipanteRow struct {
	Idparticipante       int32          `json:"idparticipante"`
	Idcliente            int32          `json:"idcliente"`
	Idreserva            int32          `json:"idreserva"`
	Fechacreacion        sql.NullTime   `json:"fechacreacion"`
	Fechaactualizacion   sql.NullTime   `json:"fechaactualizacion"`
	Clientenombre        string         `json:"clientenombre"`
	Clienteidentificador string         `json:"clienteidentificador"`
	Clientetelefono      string         `json:"clientetelefono"`
	Clientenacionalidad  string         `json:"clientenacionalidad"`
	Clientefechanac      time.Time      `json:"clientefechanac"`
	Empresanombre        sql.NullString `json:"empresanombre"`
	Empresacedula        sql.NullString `json:"empresacedula"`
	Nombreestado         string         `json:"nombreestado"`
	Tournombre           string         `json:"tournombre"`
	Fechatour            time.Time      `json:"fechatour"`
}

func (q *Queries) GetAllParticipante(ctx context.Context) ([]GetAllParticipanteRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllParticipante)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllParticipanteRow
	for rows.Next() {
		var i GetAllParticipanteRow
		if err := rows.Scan(
			&i.Idparticipante,
			&i.Idcliente,
			&i.Idreserva,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
			&i.Clientenombre,
			&i.Clienteidentificador,
			&i.Clientetelefono,
			&i.Clientenacionalidad,
			&i.Clientefechanac,
			&i.Empresanombre,
			&i.Empresacedula,
			&i.Nombreestado,
			&i.Tournombre,
			&i.Fechatour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipanteByCliente = `-- name: GetParticipanteByCliente :many
SELECT
    p.idParticipante,
    p.idCliente,
    p.idReserva,
    p.fechaCreacion,
    p.fechaActualizacion,

    e.nombre    AS nombreEstado,
    t.nombre    AS tourNombre,
    dr.fechaTour,
    dr.precioUnitario

FROM Participante p

JOIN Reserva r          ON p.idReserva          = r.idReserva
JOIN EstadoReserva e    ON r.idEstadoReserva    = e.idEstadoReserva
JOIN DetalleReserva dr  ON r.idReserva          = dr.idReserva
JOIN Tour t             ON dr.idTour            = t.idTour

WHERE p.idCliente = ?
`

type GetParticipanteByClienteRow struct {
	Idparticipante     int32        `json:"idparticipante"`
	Idcliente          int32        `json:"idcliente"`
	Idreserva          int32        `json:"idreserva"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
	Nombreestado       string       `json:"nombreestado"`
	Tournombre         string       `json:"tournombre"`
	Fechatour          time.Time    `json:"fechatour"`
	Preciounitario     string       `json:"preciounitario"`
}

func (q *Queries) GetParticipanteByCliente(ctx context.Context, idcliente int32) ([]GetParticipanteByClienteRow, error) {
	rows, err := q.db.QueryContext(ctx, getParticipanteByCliente, idcliente)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetParticipanteByClienteRow
	for rows.Next() {
		var i GetParticipanteByClienteRow
		if err := rows.Scan(
			&i.Idparticipante,
			&i.Idcliente,
			&i.Idreserva,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
			&i.Nombreestado,
			&i.Tournombre,
			&i.Fechatour,
			&i.Preciounitario,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipanteById = `-- name: GetParticipanteById :one
SELECT
    p.idParticipante,
    p.idCliente,
    p.idReserva,
    p.fechaCreacion,
    p.fechaActualizacion,

    c.nombre            AS clienteNombre,
    c.identificador     AS clienteIdentificador,
    c.telefono          AS clienteTelefono,
    c.nacionalidad      AS clienteNacionalidad,
    c.fechaNac          AS clienteFechaNac,

    ec.razonSocial      AS empresaNombre,
    ec.cedulaJuridica   AS empresaCedula,

    e.nombre            AS nombreEstado,

    t.nombre            AS tourNombre,
    dr.fechaTour

FROM Participante p

JOIN Cliente c              ON p.idCliente          = c.idCliente
JOIN Reserva r              ON p.idReserva          = r.idReserva
JOIN EstadoReserva e        ON r.idEstadoReserva    = e.idEstadoReserva
JOIN DetalleReserva dr      ON r.idReserva          = dr.idReserva
JOIN Tour t                 ON dr.idTour            = t.idTour
LEFT JOIN EmpresaCliente ec ON c.idEmpresaCliente   = ec.idEmpresaCliente

WHERE p.idParticipante = ?
`

type GetParticipanteByIdRow struct {
	Idparticipante       int32          `json:"idparticipante"`
	Idcliente            int32          `json:"idcliente"`
	Idreserva            int32          `json:"idreserva"`
	Fechacreacion        sql.NullTime   `json:"fechacreacion"`
	Fechaactualizacion   sql.NullTime   `json:"fechaactualizacion"`
	Clientenombre        string         `json:"clientenombre"`
	Clienteidentificador string         `json:"clienteidentificador"`
	Clientetelefono      string         `json:"clientetelefono"`
	Clientenacionalidad  string         `json:"clientenacionalidad"`
	Clientefechanac      time.Time      `json:"clientefechanac"`
	Empresanombre        sql.NullString `json:"empresanombre"`
	Empresacedula        sql.NullString `json:"empresacedula"`
	Nombreestado         string         `json:"nombreestado"`
	Tournombre           string         `json:"tournombre"`
	Fechatour            time.Time      `json:"fechatour"`
}

func (q *Queries) GetParticipanteById(ctx context.Context, idparticipante int32) (GetParticipanteByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getParticipanteById, idparticipante)
	var i GetParticipanteByIdRow
	err := row.Scan(
		&i.Idparticipante,
		&i.Idcliente,
		&i.Idreserva,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
		&i.Clientenombre,
		&i.Clienteidentificador,
		&i.Clientetelefono,
		&i.Clientenacionalidad,
		&i.Clientefechanac,
		&i.Empresanombre,
		&i.Empresacedula,
		&i.Nombreestado,
		&i.Tournombre,
		&i.Fechatour,
	)
	return i, err
}

const getParticipanteByReserva = `-- name: GetParticipanteByReserva :many
SELECT
    p.idParticipante,
    p.idCliente,
    p.idReserva,
    p.fechaCreacion,
    p.fechaActualizacion,

    c.nombre            AS clienteNombre,
    c.identificador     AS clienteIdentificador,
    c.telefono          AS clienteTelefono,
    c.nacionalidad      AS clienteNacionalidad,
    c.fechaNac          AS clienteFechaNac,

    ec.razonSocial      AS empresaNombre,
    ec.cedulaJuridica   AS empresaCedula

FROM Participante p

JOIN Cliente c              ON p.idCliente        = c.idCliente
LEFT JOIN EmpresaCliente ec ON c.idEmpresaCliente = ec.idEmpresaCliente

WHERE p.idReserva = ?
`

type GetParticipanteByReservaRow struct {
	Idparticipante       int32          `json:"idparticipante"`
	Idcliente            int32          `json:"idcliente"`
	Idreserva            int32          `json:"idreserva"`
	Fechacreacion        sql.NullTime   `json:"fechacreacion"`
	Fechaactualizacion   sql.NullTime   `json:"fechaactualizacion"`
	Clientenombre        string         `json:"clientenombre"`
	Clienteidentificador string         `json:"clienteidentificador"`
	Clientetelefono      string         `json:"clientetelefono"`
	Clientenacionalidad  string         `json:"clientenacionalidad"`
	Clientefechanac      time.Time      `json:"clientefechanac"`
	Empresanombre        sql.NullString `json:"empresanombre"`
	Empresacedula        sql.NullString `json:"empresacedula"`
}

func (q *Queries) GetParticipanteByReserva(ctx context.Context, idreserva int32) ([]GetParticipanteByReservaRow, error) {
	rows, err := q.db.QueryContext(ctx, getParticipanteByReserva, idreserva)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetParticipanteByReservaRow
	for rows.Next() {
		var i GetParticipanteByReservaRow
		if err := rows.Scan(
			&i.Idparticipante,
			&i.Idcliente,
			&i.Idreserva,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
			&i.Clientenombre,
			&i.Clienteidentificador,
			&i.Clientetelefono,
			&i.Clientenacionalidad,
			&i.Clientefechanac,
			&i.Empresanombre,
			&i.Empresacedula,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
