// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: participante.sql

package dto

import (
	"context"
	"database/sql"
	"time"
)

const createParticipante = `-- name: CreateParticipante :execresult
INSERT INTO Participante (
    idReserva,
    nombre,
    fechaNac,
    nacionalidad,
    telefono,
    fechaCreacion,
    fechaActualizacion
)
VALUES (?, ?, ?, ?, ?, now(), now())
`

type CreateParticipanteParams struct {
	Idreserva    int32     `json:"idreserva"`
	Nombre       string    `json:"nombre"`
	Fechanac     time.Time `json:"fechanac"`
	Nacionalidad string    `json:"nacionalidad"`
	Telefono     int32     `json:"telefono"`
}

func (q *Queries) CreateParticipante(ctx context.Context, arg CreateParticipanteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createParticipante,
		arg.Idreserva,
		arg.Nombre,
		arg.Fechanac,
		arg.Nacionalidad,
		arg.Telefono,
	)
}

const deleteParticipante = `-- name: DeleteParticipante :execresult
DELETE FROM Participante WHERE idParticipante = ?
`

func (q *Queries) DeleteParticipante(ctx context.Context, idparticipante int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteParticipante, idparticipante)
}

const getAllParticipante = `-- name: GetAllParticipante :many
SELECT idparticipante, idreserva, nombre, fechanac, nacionalidad, telefono, fechacreacion, fechaactualizacion FROM Participante
`

func (q *Queries) GetAllParticipante(ctx context.Context) ([]Participante, error) {
	rows, err := q.db.QueryContext(ctx, getAllParticipante)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participante
	for rows.Next() {
		var i Participante
		if err := rows.Scan(
			&i.Idparticipante,
			&i.Idreserva,
			&i.Nombre,
			&i.Fechanac,
			&i.Nacionalidad,
			&i.Telefono,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipanteById = `-- name: GetParticipanteById :one
SELECT idparticipante, idreserva, nombre, fechanac, nacionalidad, telefono, fechacreacion, fechaactualizacion FROM Participante WHERE idParticipante = ?
`

func (q *Queries) GetParticipanteById(ctx context.Context, idparticipante int32) (Participante, error) {
	row := q.db.QueryRowContext(ctx, getParticipanteById, idparticipante)
	var i Participante
	err := row.Scan(
		&i.Idparticipante,
		&i.Idreserva,
		&i.Nombre,
		&i.Fechanac,
		&i.Nacionalidad,
		&i.Telefono,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const updateParticipante = `-- name: UpdateParticipante :execresult
UPDATE Participante
SET idReserva = ?,
    nombre = ?,
    fechaNac = ?,
    nacionalidad = ?,
    telefono = ?,
    fechaActualizacion = now()
WHERE idParticipante = ?
`

type UpdateParticipanteParams struct {
	Idreserva      int32     `json:"idreserva"`
	Nombre         string    `json:"nombre"`
	Fechanac       time.Time `json:"fechanac"`
	Nacionalidad   string    `json:"nacionalidad"`
	Telefono       int32     `json:"telefono"`
	Idparticipante int32     `json:"idparticipante"`
}

func (q *Queries) UpdateParticipante(ctx context.Context, arg UpdateParticipanteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateParticipante,
		arg.Idreserva,
		arg.Nombre,
		arg.Fechanac,
		arg.Nacionalidad,
		arg.Telefono,
		arg.Idparticipante,
	)
}
