// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reserva.sql

package dto

import (
	"context"
	"database/sql"
)

const createReserva = `-- name: CreateReserva :execresult
INSERT INTO Reserva (
    idCliente,
    idTour,
    idGuia,
    idTransporte,
    idUbicacion,
    idIdioma,
    cantidadPersonas,
    fechaCreacion,
    fechaActualizacion
)
VALUES (?, ?, ?, ?, ?, ?, ?, now(), now())
`

type CreateReservaParams struct {
	Idcliente        int32 `json:"idcliente"`
	Idtour           int32 `json:"idtour"`
	Idguia           int32 `json:"idguia"`
	Idtransporte     int32 `json:"idtransporte"`
	Idubicacion      int32 `json:"idubicacion"`
	Ididioma         int32 `json:"ididioma"`
	Cantidadpersonas int32 `json:"cantidadpersonas"`
}

func (q *Queries) CreateReserva(ctx context.Context, arg CreateReservaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReserva,
		arg.Idcliente,
		arg.Idtour,
		arg.Idguia,
		arg.Idtransporte,
		arg.Idubicacion,
		arg.Ididioma,
		arg.Cantidadpersonas,
	)
}

const deleteReserva = `-- name: DeleteReserva :execresult
DELETE FROM Reserva WHERE idReserva = ?
`

func (q *Queries) DeleteReserva(ctx context.Context, idreserva int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteReserva, idreserva)
}

const getAllReserva = `-- name: GetAllReserva :many
SELECT 
    r.idReserva,
    r.cantidadPersonas,
    r.fechaCreacion,
    r.fechaActualizacion,

    -- Cliente
    c.nombre AS clienteNombre,
    c.telefono AS clienteTelefono,

    -- Tour
    t.nombre AS tourNombre,
    t.horario,
    t.duracion,

    -- Guia
    g.nombre AS guiaNombre,
    g.telefono AS guiaTelefono,

    -- Chofer (desde Transporte)
    ch.nombre AS choferNombre,
    ch.telefono AS choferTelefono,

    -- Ubicacion
    u.nombre AS ubicacionNombre,
    u.direccion,

    -- Idioma
    i.nombre AS idiomaNombre

FROM Reserva r

JOIN Cliente c ON r.idCliente = c.idCliente
JOIN Tour t ON r.idTour = t.idTour
JOIN Guia g ON r.idGuia = g.idGuia
JOIN Transporte tr ON r.idTransporte = tr.idTransporte
JOIN Chofer ch ON tr.idChofer = ch.idChofer
JOIN Ubicacion u ON r.idUbicacion = u.idUbicacion
JOIN Idioma i ON r.idIdioma = i.idIdioma
`

type GetAllReservaRow struct {
	Idreserva          int32        `json:"idreserva"`
	Cantidadpersonas   int32        `json:"cantidadpersonas"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
	Clientenombre      string       `json:"clientenombre"`
	Clientetelefono    int32        `json:"clientetelefono"`
	Tournombre         string       `json:"tournombre"`
	Horario            string       `json:"horario"`
	Duracion           int32        `json:"duracion"`
	Guianombre         string       `json:"guianombre"`
	Guiatelefono       int32        `json:"guiatelefono"`
	Chofernombre       string       `json:"chofernombre"`
	Chofertelefono     int32        `json:"chofertelefono"`
	Ubicacionnombre    string       `json:"ubicacionnombre"`
	Direccion          string       `json:"direccion"`
	Idiomanombre       string       `json:"idiomanombre"`
}

func (q *Queries) GetAllReserva(ctx context.Context) ([]GetAllReservaRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllReserva)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllReservaRow
	for rows.Next() {
		var i GetAllReservaRow
		if err := rows.Scan(
			&i.Idreserva,
			&i.Cantidadpersonas,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
			&i.Clientenombre,
			&i.Clientetelefono,
			&i.Tournombre,
			&i.Horario,
			&i.Duracion,
			&i.Guianombre,
			&i.Guiatelefono,
			&i.Chofernombre,
			&i.Chofertelefono,
			&i.Ubicacionnombre,
			&i.Direccion,
			&i.Idiomanombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservaById = `-- name: GetReservaById :one
SELECT idreserva, idcliente, idtour, idguia, idtransporte, idubicacion, ididioma, cantidadpersonas, fechacreacion, fechaactualizacion FROM Reserva WHERE idReserva = ?
`

func (q *Queries) GetReservaById(ctx context.Context, idreserva int32) (Reserva, error) {
	row := q.db.QueryRowContext(ctx, getReservaById, idreserva)
	var i Reserva
	err := row.Scan(
		&i.Idreserva,
		&i.Idcliente,
		&i.Idtour,
		&i.Idguia,
		&i.Idtransporte,
		&i.Idubicacion,
		&i.Ididioma,
		&i.Cantidadpersonas,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const updateReserva = `-- name: UpdateReserva :execresult
UPDATE Reserva
SET idCliente = ?,
    idTour = ?,
    idGuia = ?,
    idTransporte = ?,
    idUbicacion = ?,
    idIdioma = ?,
    cantidadPersonas = ?,
    fechaActualizacion = now()
WHERE idReserva = ?
`

type UpdateReservaParams struct {
	Idcliente        int32 `json:"idcliente"`
	Idtour           int32 `json:"idtour"`
	Idguia           int32 `json:"idguia"`
	Idtransporte     int32 `json:"idtransporte"`
	Idubicacion      int32 `json:"idubicacion"`
	Ididioma         int32 `json:"ididioma"`
	Cantidadpersonas int32 `json:"cantidadpersonas"`
	Idreserva        int32 `json:"idreserva"`
}

func (q *Queries) UpdateReserva(ctx context.Context, arg UpdateReservaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateReserva,
		arg.Idcliente,
		arg.Idtour,
		arg.Idguia,
		arg.Idtransporte,
		arg.Idubicacion,
		arg.Ididioma,
		arg.Cantidadpersonas,
		arg.Idreserva,
	)
}
