// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tour.sql

package dto

import (
	"context"
	"database/sql"
)

const createTour = `-- name: CreateTour :execresult
INSERT INTO Tour (
    nombre, 
    descripcion, 
    horario, 
    duracion, 
    cuposMaximos, 
    precioBase, 
    fechaCreacion, 
    fechaActualizacion
) VALUES (?, ?, ?, ?, ?, ?, now(), now())
`

type CreateTourParams struct {
	Nombre       string  `json:"nombre"`
	Descripcion  string  `json:"descripcion"`
	Horario      string  `json:"horario"`
	Duracion     int32   `json:"duracion"`
	Cuposmaximos int32   `json:"cuposmaximos"`
	Preciobase   float64 `json:"preciobase"`
}

func (q *Queries) CreateTour(ctx context.Context, arg CreateTourParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTour,
		arg.Nombre,
		arg.Descripcion,
		arg.Horario,
		arg.Duracion,
		arg.Cuposmaximos,
		arg.Preciobase,
	)
}

const deleteTour = `-- name: DeleteTour :execresult
DELETE FROM Tour WHERE idTour = ?
`

func (q *Queries) DeleteTour(ctx context.Context, idtour int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTour, idtour)
}

const getAllTours = `-- name: GetAllTours :many
SELECT idtour, nombre, descripcion, horario, duracion, cuposmaximos, preciobase, fechacreacion, fechaactualizacion FROM Tour
`

func (q *Queries) GetAllTours(ctx context.Context) ([]Tour, error) {
	rows, err := q.db.QueryContext(ctx, getAllTours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tour
	for rows.Next() {
		var i Tour
		if err := rows.Scan(
			&i.Idtour,
			&i.Nombre,
			&i.Descripcion,
			&i.Horario,
			&i.Duracion,
			&i.Cuposmaximos,
			&i.Preciobase,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTourById = `-- name: GetTourById :one
SELECT idtour, nombre, descripcion, horario, duracion, cuposmaximos, preciobase, fechacreacion, fechaactualizacion FROM Tour WHERE idTour = ?
`

func (q *Queries) GetTourById(ctx context.Context, idtour int32) (Tour, error) {
	row := q.db.QueryRowContext(ctx, getTourById, idtour)
	var i Tour
	err := row.Scan(
		&i.Idtour,
		&i.Nombre,
		&i.Descripcion,
		&i.Horario,
		&i.Duracion,
		&i.Cuposmaximos,
		&i.Preciobase,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const updateTour = `-- name: UpdateTour :execresult
UPDATE Tour 
SET nombre = ?, 
    descripcion = ?, 
    horario = ?, 
    duracion = ?, 
    cuposMaximos = ?, 
    precioBase = ?, 
    fechaActualizacion = now()
WHERE idTour = ?
`

type UpdateTourParams struct {
	Nombre       string  `json:"nombre"`
	Descripcion  string  `json:"descripcion"`
	Horario      string  `json:"horario"`
	Duracion     int32   `json:"duracion"`
	Cuposmaximos int32   `json:"cuposmaximos"`
	Preciobase   float64 `json:"preciobase"`
	Idtour       int32   `json:"idtour"`
}

func (q *Queries) UpdateTour(ctx context.Context, arg UpdateTourParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTour,
		arg.Nombre,
		arg.Descripcion,
		arg.Horario,
		arg.Duracion,
		arg.Cuposmaximos,
		arg.Preciobase,
		arg.Idtour,
	)
}
