// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transporte.sql

package dto

import (
	"context"
	"database/sql"
)

const createTransporte = `-- name: CreateTransporte :execresult
INSERT INTO transporte (idChofer, fechaCreacion, fechaActualizacion)
VALUES (?, NOW(), NOW())
`

func (q *Queries) CreateTransporte(ctx context.Context, idchofer int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTransporte, idchofer)
}

const deleteTransporte = `-- name: DeleteTransporte :execresult
DELETE FROM transporte WHERE idTransporte = ?
`

func (q *Queries) DeleteTransporte(ctx context.Context, idtransporte int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTransporte, idtransporte)
}

const getAllTransporte = `-- name: GetAllTransporte :many
SELECT idtransporte, idchofer, fechacreacion, fechaactualizacion FROM transporte
`

func (q *Queries) GetAllTransporte(ctx context.Context) ([]Transporte, error) {
	rows, err := q.db.QueryContext(ctx, getAllTransporte)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transporte
	for rows.Next() {
		var i Transporte
		if err := rows.Scan(
			&i.Idtransporte,
			&i.Idchofer,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransporteById = `-- name: GetTransporteById :one
SELECT idtransporte, idchofer, fechacreacion, fechaactualizacion FROM transporte WHERE idTransporte = ?
`

func (q *Queries) GetTransporteById(ctx context.Context, idtransporte int32) (Transporte, error) {
	row := q.db.QueryRowContext(ctx, getTransporteById, idtransporte)
	var i Transporte
	err := row.Scan(
		&i.Idtransporte,
		&i.Idchofer,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const updateTransporte = `-- name: UpdateTransporte :execresult
UPDATE transporte
SET idChofer = ?,
    fechaActualizacion = NOW()
WHERE idTransporte = ?
`

type UpdateTransporteParams struct {
	Idchofer     int32 `json:"idchofer"`
	Idtransporte int32 `json:"idtransporte"`
}

func (q *Queries) UpdateTransporte(ctx context.Context, arg UpdateTransporteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTransporte, arg.Idchofer, arg.Idtransporte)
}
