// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ubicacion.sql

package dto

import (
	"context"
	"database/sql"
)

const createUbicacion = `-- name: CreateUbicacion :execresult
INSERT INTO ubicacion (nombre, direccion, fechaCreacion, fechaActualizacion)
VALUES (?, ?, now(), now())
`

type CreateUbicacionParams struct {
	Nombre    string `json:"nombre"`
	Direccion string `json:"direccion"`
}

func (q *Queries) CreateUbicacion(ctx context.Context, arg CreateUbicacionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUbicacion, arg.Nombre, arg.Direccion)
}

const deleteUbicacion = `-- name: DeleteUbicacion :execresult
DELETE FROM ubicacion WHERE idUbicacion = ?
`

func (q *Queries) DeleteUbicacion(ctx context.Context, idubicacion int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUbicacion, idubicacion)
}

const getAllUbicacion = `-- name: GetAllUbicacion :many
SELECT idubicacion, nombre, direccion, fechacreacion, fechaactualizacion FROM ubicacion
`

func (q *Queries) GetAllUbicacion(ctx context.Context) ([]Ubicacion, error) {
	rows, err := q.db.QueryContext(ctx, getAllUbicacion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ubicacion
	for rows.Next() {
		var i Ubicacion
		if err := rows.Scan(
			&i.Idubicacion,
			&i.Nombre,
			&i.Direccion,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUbicacionById = `-- name: GetUbicacionById :one
SELECT idubicacion, nombre, direccion, fechacreacion, fechaactualizacion FROM ubicacion WHERE idUbicacion = ?
`

func (q *Queries) GetUbicacionById(ctx context.Context, idubicacion int32) (Ubicacion, error) {
	row := q.db.QueryRowContext(ctx, getUbicacionById, idubicacion)
	var i Ubicacion
	err := row.Scan(
		&i.Idubicacion,
		&i.Nombre,
		&i.Direccion,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const updateUbicacion = `-- name: UpdateUbicacion :execresult
UPDATE ubicacion
SET nombre                = ?,
    direccion              = ?,
    fechaActualizacion     = now()
WHERE idUbicacion = ?
`

type UpdateUbicacionParams struct {
	Nombre      string `json:"nombre"`
	Direccion   string `json:"direccion"`
	Idubicacion int32  `json:"idubicacion"`
}

func (q *Queries) UpdateUbicacion(ctx context.Context, arg UpdateUbicacionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUbicacion, arg.Nombre, arg.Direccion, arg.Idubicacion)
}
