// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usuario.sql

package dto

import (
	"context"
	"database/sql"
)

const createUsuario = `-- name: CreateUsuario :execresult
INSERT INTO usuarios (nombre, apellido, rol, correo, contrasena, descripcion, imagen, fechacreacion, fechaactualizacion)
VALUES (?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
`

type CreateUsuarioParams struct {
	Nombre      string         `json:"nombre"`
	Apellido    sql.NullString `json:"apellido"`
	Rol         sql.NullString `json:"rol"`
	Correo      string         `json:"correo"`
	Contrasena  string         `json:"contrasena"`
	Descripcion sql.NullString `json:"descripcion"`
	Imagen      sql.NullString `json:"imagen"`
}

func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUsuario,
		arg.Nombre,
		arg.Apellido,
		arg.Rol,
		arg.Correo,
		arg.Contrasena,
		arg.Descripcion,
		arg.Imagen,
	)
}

const deleteUsuario = `-- name: DeleteUsuario :exec
DELETE FROM usuarios WHERE idusuario = ?
`

func (q *Queries) DeleteUsuario(ctx context.Context, idusuario int32) error {
	_, err := q.db.ExecContext(ctx, deleteUsuario, idusuario)
	return err
}

const getAllUsuarios = `-- name: GetAllUsuarios :many
SELECT idusuario, nombre, apellido, rol, correo, contrasena, descripcion, imagen, fechacreacion, fechaactualizacion, tokenrecordar FROM usuarios
`

func (q *Queries) GetAllUsuarios(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.Idusuario,
			&i.Nombre,
			&i.Apellido,
			&i.Rol,
			&i.Correo,
			&i.Contrasena,
			&i.Descripcion,
			&i.Imagen,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
			&i.Tokenrecordar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT idusuario, nombre, apellido, rol, correo, contrasena, descripcion, imagen, fechacreacion, fechaactualizacion, tokenrecordar FROM usuarios WHERE correo=? limit 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, correo string) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, correo)
	var i Usuario
	err := row.Scan(
		&i.Idusuario,
		&i.Nombre,
		&i.Apellido,
		&i.Rol,
		&i.Correo,
		&i.Contrasena,
		&i.Descripcion,
		&i.Imagen,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
		&i.Tokenrecordar,
	)
	return i, err
}

const updateUsuario = `-- name: UpdateUsuario :exec
UPDATE usuarios SET 
    nombre = ?,
    apellido = ?,
    rol = ?,
    correo = ?,
    contrasena = ?,
    descripcion = ?,
    imagen = ?,
    fechaactualizacion = NOW()
WHERE idusuario = ?
`

type UpdateUsuarioParams struct {
	Nombre      string         `json:"nombre"`
	Apellido    sql.NullString `json:"apellido"`
	Rol         sql.NullString `json:"rol"`
	Correo      string         `json:"correo"`
	Contrasena  string         `json:"contrasena"`
	Descripcion sql.NullString `json:"descripcion"`
	Imagen      sql.NullString `json:"imagen"`
	Idusuario   int32          `json:"idusuario"`
}

func (q *Queries) UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) error {
	_, err := q.db.ExecContext(ctx, updateUsuario,
		arg.Nombre,
		arg.Apellido,
		arg.Rol,
		arg.Correo,
		arg.Contrasena,
		arg.Descripcion,
		arg.Imagen,
		arg.Idusuario,
	)
	return err
}
