// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehiculo.sql

package dto

import (
	"context"
	"database/sql"
)

const createVehiculo = `-- name: CreateVehiculo :execresult
INSERT INTO Vehiculo (
    idChofer, 
    matricula, 
    capacidad, 
    modelo, 
    fechaCreacion, 
    fechaActualizacion
) VALUES (?, ?, ?, ?, now(), now())
`

type CreateVehiculoParams struct {
	Idchofer  int32  `json:"idchofer"`
	Matricula string `json:"matricula"`
	Capacidad int32  `json:"capacidad"`
	Modelo    string `json:"modelo"`
}

func (q *Queries) CreateVehiculo(ctx context.Context, arg CreateVehiculoParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createVehiculo,
		arg.Idchofer,
		arg.Matricula,
		arg.Capacidad,
		arg.Modelo,
	)
}

const deleteVehiculo = `-- name: DeleteVehiculo :execresult
DELETE FROM Vehiculo WHERE idVehiculo = ?
`

func (q *Queries) DeleteVehiculo(ctx context.Context, idvehiculo int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteVehiculo, idvehiculo)
}

const getAllVehiculos = `-- name: GetAllVehiculos :many
SELECT 
    v.idVehiculo, 
    v.matricula, 
    v.capacidad, 
    v.modelo, 
    v.idChofer, 
    c.nombre AS nombre_chofer,
    c.telefono AS telefono_chofer,
    v.fechaCreacion,
    v.fechaActualizacion
FROM Vehiculo v
JOIN Chofer c ON v.idChofer = c.idChofer
`

type GetAllVehiculosRow struct {
	Idvehiculo         int32        `json:"idvehiculo"`
	Matricula          string       `json:"matricula"`
	Capacidad          int32        `json:"capacidad"`
	Modelo             string       `json:"modelo"`
	Idchofer           int32        `json:"idchofer"`
	NombreChofer       string       `json:"nombre_chofer"`
	TelefonoChofer     string       `json:"telefono_chofer"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
}

func (q *Queries) GetAllVehiculos(ctx context.Context) ([]GetAllVehiculosRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllVehiculos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllVehiculosRow
	for rows.Next() {
		var i GetAllVehiculosRow
		if err := rows.Scan(
			&i.Idvehiculo,
			&i.Matricula,
			&i.Capacidad,
			&i.Modelo,
			&i.Idchofer,
			&i.NombreChofer,
			&i.TelefonoChofer,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVehiculoById = `-- name: GetVehiculoById :one
SELECT
    v.idVehiculo,
    v.matricula,
    v.capacidad,
    v.modelo,
    v.idChofer,
    c.nombre AS nombre_chofer,
    c.telefono AS telefono_chofer,
    v.fechaCreacion,
    v.fechaActualizacion
FROM Vehiculo v
JOIN Chofer c
    ON v.idChofer = c.idChofer
WHERE v.idVehiculo = ?
`

type GetVehiculoByIdRow struct {
	Idvehiculo         int32        `json:"idvehiculo"`
	Matricula          string       `json:"matricula"`
	Capacidad          int32        `json:"capacidad"`
	Modelo             string       `json:"modelo"`
	Idchofer           int32        `json:"idchofer"`
	NombreChofer       string       `json:"nombre_chofer"`
	TelefonoChofer     string       `json:"telefono_chofer"`
	Fechacreacion      sql.NullTime `json:"fechacreacion"`
	Fechaactualizacion sql.NullTime `json:"fechaactualizacion"`
}

func (q *Queries) GetVehiculoById(ctx context.Context, idvehiculo int32) (GetVehiculoByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getVehiculoById, idvehiculo)
	var i GetVehiculoByIdRow
	err := row.Scan(
		&i.Idvehiculo,
		&i.Matricula,
		&i.Capacidad,
		&i.Modelo,
		&i.Idchofer,
		&i.NombreChofer,
		&i.TelefonoChofer,
		&i.Fechacreacion,
		&i.Fechaactualizacion,
	)
	return i, err
}

const getVehiculosByChofer = `-- name: GetVehiculosByChofer :many
SELECT idvehiculo, idchofer, matricula, capacidad, modelo, fechacreacion, fechaactualizacion FROM Vehiculo 
WHERE idChofer = ?
`

func (q *Queries) GetVehiculosByChofer(ctx context.Context, idchofer int32) ([]Vehiculo, error) {
	rows, err := q.db.QueryContext(ctx, getVehiculosByChofer, idchofer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vehiculo
	for rows.Next() {
		var i Vehiculo
		if err := rows.Scan(
			&i.Idvehiculo,
			&i.Idchofer,
			&i.Matricula,
			&i.Capacidad,
			&i.Modelo,
			&i.Fechacreacion,
			&i.Fechaactualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehiculo = `-- name: UpdateVehiculo :execresult
UPDATE Vehiculo 
SET idChofer = ?,
    matricula = ?, 
    capacidad = ?, 
    modelo = ?, 
    fechaActualizacion = now()
WHERE idVehiculo = ?
`

type UpdateVehiculoParams struct {
	Idchofer   int32  `json:"idchofer"`
	Matricula  string `json:"matricula"`
	Capacidad  int32  `json:"capacidad"`
	Modelo     string `json:"modelo"`
	Idvehiculo int32  `json:"idvehiculo"`
}

func (q *Queries) UpdateVehiculo(ctx context.Context, arg UpdateVehiculoParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateVehiculo,
		arg.Idchofer,
		arg.Matricula,
		arg.Capacidad,
		arg.Modelo,
		arg.Idvehiculo,
	)
}
